### ISSUE TITLE
upload more than one file

### ISSUE THREAD

**Issue by kimgerdes** [Arborator/arborator-frontend#1]
choisir plus d'un fichier à la fois à téléverser me donne ceci comme erreur : 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://arborapi.ilpga.fr:8888/api/projects/Naija/upload. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).TypeError: a.response is undefined

**Comment by gguibon** [comment]
Fixed using selection or drag and drop
