### ISSUE TITLE
Deprel as "_" in the conllu input leads to an error

### ISSUE THREAD

**Issue by gguibon** [Arborator/arborator-frontend#104]
It would be nice to be able to upload empty "_" deprel other thant the root (0).

For the moment it returns the following error from Grew I suppose : 
```
werkzeug.exceptions.ImATeapot: 418 I'm a teapot: Problem in your Conll file “99”<br>Invalid HEAD/DEPREL spec<br>This line looks fishy:<br><code>6	eto	eto	ADV	_	_	5	_	_	_
</code>
```
and it can only be worked around by using a space " " or "unk" for the unknown deprel.

Some users would like to enable the "_" as well.

**Comment by gguibon** [comment]
@bguil I assigned you for the moment just to ensure this is a Grew issue or not. Feel free to change the assignment if needed. :)

**Comment by bguil** [comment]
Fix "_" is accepted as an empty DEPREL.
It's available in DEV and will be in PROD on the next update.
