### ISSUE TITLE
Addition of files to a project

### ISSUE THREAD

**Issue by perrier54** [Arborator/arborator-frontend#11]
I created a project and added a file to the project, but I can't add a second file. It seems that the problem is due to the size of the file (641kb for the first file and 2.1MB for the second).

**Comment by kimgerdes** [comment]
i cannot reproduce your error. I tried with the biggest file i could find on UD, https://github.com/UniversalDependencies/UD_German-HDT/blob/master/de_hdt-ud-train-a-1.conllu and it worked. now i have a sample with 38k sentences :)
can you explore a bit further when the problem appears, please?

**Comment by perrier54** [comment]
Even if there is no file in the project, I cannot add the following file (I had to rename it because the conll extension is denied by github).
[fr_gsd-sud-dev_sud.txt](https://github.com/Arborator/arborator-frontend/files/4664408/fr_gsd-sud-dev_sud.txt)

**Comment by kimgerdes** [comment]
indeed.
it works in development but not in prod.
i get this:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://arborapi.ilpga.fr:8888/api/projects/voyons/upload. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
TypeError: n.response is undefined
@gguibon could you look into this?

**Comment by gguibon** [comment]
Problem solved. Max content allowed set to 5MB. Please ask for more if needed.

**Comment by perrier54** [comment]
It works but the 5MB limit is too low. It is not possible to add the whole French corpus of the GSB.
