### ISSUE TITLE
Grew search : give more possibilities for querying tree of users

### ISSUE THREAD

**Issue by kirianguiller** [Arborator/arborator-frontend#110]
We want to give these possibilities when doing grew search (similarly as the choices for table of deprel):
- See for my trees
- See for my trees or last tree (only one user_id per tree is returned)
- See last trees
- See trees from everyone
Bonus : 
- See trees for users in a given list

**Comment by bguil** [comment]
Done in DEV: see [Grew server doc](https://grew.fr/usage/grew_server/#user_ids-changed-on-220126).

Note that this implies:
 * [ ] changes in the Flask code, for each usage of the `user_ids` parameter.

A tmp mapping with the old definition of `user_ids` is available and will be removed once Flask is updated.

**Comment by kirianguiller** [comment]
I tried the new syntax, and I receive a grew error (``user_ids` parameter is not a valid JSON data`). The old syntax still works.

New syntax : 
```json
{'project_id': 'test_arbre_access', 'pattern': '% Search for a given word form\npattern { N [form="Port"] }', 'user_ids': 'all'}
```

Old syntax : 
```json
{'project_id': 'test_arbre_access', 'pattern': '% Search for a given word form\npattern { N [form="Port"] }', 'user_ids': '[]'}
```

**Comment by bguil** [comment]
The value of `user_ids` must be the encoding of the JSON string, not the string: hence `"all"` and not `all`.

Other strings, like `project_id` or `pattern` are not supposed to be JSON, that's explain the difference.

**Comment by bguil** [comment]
`{'multi': ['kirianguiller', 'kiriangui']}` is not a valid JSON syntax. It should be `{"multi": ["kirianguiller", "kiriangui"]}` (tested on https://jsonchecker.com/)

**Comment by kirianguiller** [comment]
user_ids should be the string representation of a json ?

I'm confused, it's working for the other parameters which are all single quoted :
```json
{
   'project_id': 'test_arbre_access', 
   'pattern': '% Search for a given word form\npattern { N [form="Port"] }',
}
```

**Comment by kirianguiller** [comment]
ah, it seems it should be the string dumps of the property, it works now : https://github.com/Arborator/arborator-backend/commit/e2acd17f6b6fb7f84b3344b5b0b3c2b9f8363099

**Comment by bguil** [comment]
Done in Grew-server and in arborator-backend
