### ISSUE TITLE
Wrong user name in import interface

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#117]
We I upload a new file in a projet, it is written: *your user name 687155* and not *bguil* (see screenshot)

Note that the user name is correct in the corpus after the import.

<img width="563" alt="Screenshot 2022-02-07 at 10 42 25" src="https://user-images.githubusercontent.com/687155/152763484-9496a615-9d88-4c33-9f15-cfde21176e98.png">

**Comment by kirianguiller** [comment]
You still have this problem @bguil ?

**Comment by bguil** [comment]
The problem is still present:

<img width="560" alt="Screenshot 2022-09-14 at 20 10 09" src="https://user-images.githubusercontent.com/687155/190230528-6441d59d-6cba-44bb-9909-2edd02418169.png">
