### ISSUE TITLE
Illegal CoNLL after a token modification

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#119]
Impossible to save a graph after a token modification.

Steps to reproduce:
 * open a sentence
 * double click on a token in the text part &rarr; the token editor is opened
 * change the text into something else
 * save &rarr; Grew error (see screenshot)

<img width="980" alt="Screenshot 2022-02-13 at 09 29 29" src="https://user-images.githubusercontent.com/687155/153745260-8c122d22-c076-43c1-92ea-4d4f0ae2e5f4.png">

 
If we have a look at the CoNLL, we observed some line(s) with a DEPREL but without HEAD (see below). This CoNLL can not be interpreted by Grew. That's why the error is returned.

```
12	-i	_	PRON	TAM, PNG	Aspect=Aor|Number=Sing|Person=1	_	subj:aff	_	AlignBegin=7352|AlignEnd=7523|GE=-[AOR].[1SG]|RX=-[TAM].[PNG]|TokenType=InflAff

```

**Comment by khansadaoudi** [comment]
fixed in this commit [74cd096](https://github.com/Arborator/arborator-frontend/commit/74cd09629c3bf9fb39a3e1991e1176912eff05b2)
