### ISSUE TITLE
Wild 'user_id' appears when querying

### ISSUE THREAD

**Issue by marinecourtin** [Arborator/arborator-frontend#12]
A fake tree from user "user_id" appears on some results when there should only be 1 tree :

____

When I go through the relation table for a project, I get the following results

![Capture d’écran de 2020-05-20 17-48-12](https://user-images.githubusercontent.com/28790155/82467589-1c753e00-9ac2-11ea-8652-c58079c4df92.png)

The weird thing is that only 1 user has this tree in the sample:

![Capture d’écran de 2020-05-20 17-55-08](https://user-images.githubusercontent.com/28790155/82468447-16cc2800-9ac3-11ea-9c63-f91a27be6527.png)

**Comment by kimgerdes** [comment]
could this be because the first use is admin?

**Comment by marinecourtin** [comment]
The issue has been fixed with the following commit : https://github.com/Arborator/arborator-flask/commit/1a6b00d095c7731310e9cf051a3f545248066399
