### ISSUE TITLE
Improve the process for adding a new token

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#123]
There are a few problems with this:

### There are two places where it is possible to add a new token.
 1. in the "tree dots" menu on the top right corner of the sentence box `Add a new token`
 2. by selecting a piece of text on the sentence above the deptree drawing

The first solution is too restricted (only adding a token at the end). I suggest to keep only the second one

### The text selection is not stable
With a double click on one work on the text, there is sometimes only one token text area and sometimes 3 (with 2 empty ones). I cannot understand how it should be used.

### The morphological information is lost
If one wants to split a token _uv_ into two separate tokens  _u_ and _v_, all the morphological information on _uv_ is lost. It would be better to duplicate the morphology on _u_ and _v_. It is easier to remove or update the data instead of having to rebuild it.

**Comment by bguil** [comment]
Ping: this is the problem we discuss yesterday (*The morphological information is lost*).

**Comment by khansadaoudi** [comment]
redundant [#184](https://github.com/Arborator/arborator-frontend/issues/184)
