### ISSUE TITLE
Feature: add the possibility to change sentence segmentation

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#126]
In the old Arborator, it was possible to merge two sentences or to split one sentence in two smaller ones.
It would useful to have this again in the new version.

**Comment by sylvainkahane** [comment]
I come back to this issue opened 20 months ago. It is really an important feature. We often face the problem of an inappropriate sentence segmentation. I have the following suggestions.

1) the splitting of a sentence into two or more sentences can be done when the sentences has already been annotated. In other word, we can authorize the splitting only if the sentence in completely annotated and has several roots. The problem concerns the metadata and the splitter must be encouraged to edit the metadata, especially sent_id (a suggestion can be done by AG) and the translation (text_en, text_fr, etc.). Eventually this can be done only when the project is exported.

2) the merging of two sentences in one can be done every time. Again the merger must be encouraged to edit the metadata, even if suggestions can be done for most metadata. This is the most important required feature. And the simplest one, I think.

**Comment by RZiane** [comment]
Hi, 
I've just tried the new feature and it seems to be bugged : 
![image](https://github.com/Arborator/arborator-frontend/assets/77019730/f3c0e2ad-5803-43dd-bef9-426d6079d02c)

For a bit of context, these are sentences generated with Arborator's built-in French tokenizer but it's also not working with a conllu of mine.

**Comment by RZiane** [comment]
I don't know if this is the right way to proceed or if I should open another feature request, but for the needs of some projects we're working with text files divided by sentence size into conllu sub-files: 
![image](https://github.com/Arborator/arborator-frontend/assets/77019730/7eeb00ce-3ad9-46dd-b187-2c41abb02e70)

Do you think it would be possible to concatenate two sentences from two conllu files in the same project?

**Comment by bguil** [comment]
You were too fast to test!
The new feature requires some update of the backend server. I will update this evening and post a new message here.
For the second message, we haven't planned to merge two sentences from two files. It seems not a very usual operation. Sentences merging should be on consecutive sentence most of the times.

**Comment by bguil** [comment]
server was restarted. The sentence splitting is available

**Comment by B-CARON** [comment]
Thanks a lot ! Very useful. I’ll test tomorrow. Bernard Caron57, avenue d’Italie75013 PARIS06 63 68 15 19 De : Bruno GuillaumeEnvoyé le :lundi 22 janvier 2024 19:41À : Arborator/arborator-frontendCc : SubscribedObjet :Re: [Arborator/arborator-frontend] Feature: add the possibility to change sentence segmentation (Issue #126) server was restarted. The sentence splitting is available—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
