### ISSUE TITLE
cookie problem after logout

### ISSUE THREAD

**Issue by kimgerdes** [Arborator/arborator-frontend#13]
after logout the admin status is not properly erased.

how to reproduce:

1. as project admin, go to project click on the cog to open the project settings. all good.
2. logout
3. go back to the project, click again on the cog, the same dialog opens! (but saving changes doesn't work). the js console gives the error below.
4. reload the page. click again on the cog. now it shows the small project information available to anyone.

same problem:
- after logout the choices of the relation table remain in admin mode even after logout.

Some cookies are misusing the recommended “sameSite“ attribute 2
Cookie “session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies vendor.js line 5908 > eval:99:30
Cookie “remember_token” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies

**Comment by gguibon** [comment]
fixed
