### ISSUE TITLE
Limitation in the number of MISC features & Editing of meta lines

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#130]
The number of MISC features that are viewed and edited in Arborator ils limited to 5. If there are more, they cannot be viewed; if there are 5 shown already, you cannot add new ones. This is a severe handicap!
NB: this seems to apply to the "edit metadata" button as well.

**Comment by kirianguiller** [comment]
We just solved this in the last commit https://github.com/Arborator/arborator-frontend/commit/1837e8bd2cfcb6e082357cb0d799a82f8583e971.

Sorry for the time it took. Please let us know if it still doesn't work on your side (CTRL + R for hard refresh of the page and to be sure of having the last version of the code).

Thanks
