### ISSUE TITLE
Token deletion doesn't always works

### ISSUE THREAD

**Issue by RZiane** [Arborator/arborator-frontend#131]
Hi, 
I have a problem with the token deletion (in the sentence above the tree, see the screenshot below). Sometimes the "trash" button does nothing and other times it deletes the token without any problem. 
I really don't understand where this could come from...
Thanks by advance.
![image](https://user-images.githubusercontent.com/77019730/175562338-4a8d9178-39eb-45e7-b15f-91f1b4dc0454.png)

**Comment by RZiane** [comment]
Btw when token deletion works well, the conllu becomes corrupted by the removal of the head, as specified in this issue https://github.com/Arborator/arborator-frontend/issues/119 . Would it be possible to set a default head, for instance 0?

**Comment by B-CARON** [comment]
I met the same problem. My solution: give a governor to the orphan head manually before saving.
