### ISSUE TITLE
"Generate Rule"-feature from sentence graph-view

### ISSUE THREAD

**Issue by Ingerid** [Arborator/arborator-frontend#132]
I would like to be able to generate Grew rules when I make changes to dependency relations in the the sentence graph interface (cf. "Generate Grew Rule" for the modified lexicon interface, https://github.com/Arborator/arborator-frontend/issues/99#issuecomment-990683072 ).  

Context: 
I am converting the [Norwegian Dependency Treebank](https://www.nb.no/sprakbanken/en/resource-catalogue/oai-nb-no-sbr-10/) to the UD v2.10 format. The NDT format has some dependency relation labels that map well to the UD format, and many that don't.

Below is an example of a conversion that is easy to write a simple rule for, changing the "FINV" relation for the head of a sentence to "root".
![image](https://user-images.githubusercontent.com/37677043/176682128-481420a4-0274-417c-9b73-faab59017575.png)

When I then go on to more elaborate changes to the structure, such as changing the root node, shifting all dependents from the old root to the new one, relabelling relations based on features etc., and changing the relation direction in many cases, I would like to generate a Grew rule for each change I make, with the features and POS-tags of the affected nodes. That would make it easier to identify the relevant properties and constraints for the graph rewriting system which I write locally and currently use the Grew CLI for.

**Comment by sylvainkahane** [comment]
Hi @Ingerid, it seems that the original format of the Norwegian DT is very close to the SUD format (see https://surfacesyntacticud.github.io/). We already have grammars converting SUD to UD (and we can help you to customize the conversion for the Norwegian if there are particularities). We are now maintaining several treebanks in the SUD format, the conversion to UD being done automatically at each update of the SUD treebank. See especially our last paper:
Kim Gerdes, Bruno Guillaume, Sylvain Kahane, Guy Perrier. [Starting a new treebank? Go SUD! Theoretical and practical benefits of the Surface-Syntactic distributional approach](https://hal.inria.fr/hal-03509136v1) in [DepLing 2021](http://depling.org/depling2021/).
If you prefer a direct conversion to UD, see the SUD2UD grammars on the SUD github.

**Comment by Ingerid** [comment]
> If you prefer a direct conversion to UD, see the SUD2UD grammars on the SUD github.

Thanks for the tip! I'll check it out :)
