### ISSUE TITLE
UD annotation scheme

### ISSUE THREAD

**Issue by RZiane** [Arborator/arborator-frontend#133]
Hi, 
Does anyone know where to find the UD annotation schema in JSON format?
To use it in a UD project.
Thanks in advance.
Rayan

**Comment by kirianguiller** [comment]
@bguil , @kimgerdes  ? Do you know where to find it ?

**Comment by bguil** [comment]
I don't know if it exists or not... Maybe one of the project on UD have built it?

Anyway it should be straightforward to write it. But the question is where to store it? and how to make it available when a new treebank is started.

**Comment by kimgerdes** [comment]
that's an important question. the most missionary would be to propose SUD by default and leave UD and other annotation schemes with DIY.
But I think that SUD and UD should be proposed directly, and the file stored just like now (in the frontend?).

I would do it like that: A new project has a SUD scheme by default. And there could be a menu with two choices next to the scheme: "reset scheme to standard SUD" and "reset scheme to standard UD" with a warning: "Are you sure to replace the current scheme by the standard one?"

@bguil could you create such a UD json file?

**Comment by bguil** [comment]
I've built it [here](https://gist.github.com/bguil/4b12560ec87ae4292f668916b7e4f858).

By the way, @kimgerdes, I don't understand what this part: https://github.com/Arborator/arborator-frontend/blob/acd7ebb4fcf189579e218e4740c9f1ec4b304751/src/pinia/modules/project/defaultState.ts#L167 of the SUD config means. Is it needed?

**Comment by khansadaoudi** [comment]
added in the commit [b8aabdc](https://github.com/Arborator/arborator-frontend/commit/b8aabdcb3402b75f141c530946d3dac1e31f3654)
