### ISSUE TITLE
Metadata cannot be edited

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#137]
The Metadata button does not display all the metadata lines of the CONLL
Those that are displayed cannot be edited (there is an error sign displaying when saving).

**Comment by kirianguiller** [comment]
```quote
Those that are displayed cannot be edited (there is an error sign displaying when saving).
```
This part is fixed

**Comment by kirianguiller** [comment]
Both problems are fixed. Please try again and let me know if the problem still occurs

**Comment by kirianguiller** [comment]
Both problems are fixed. Please try again and let us know if the problem still occurs
