### ISSUE TITLE
Problem to access Arborator Quick Edit

### ISSUE THREAD

**Issue by adripag** [Arborator/arborator-frontend#140]
For several weeks now, I have tried to use Arborator Quick Edit (CoNLL files graphical editor) but keep getting this message: Not Found
The requested URL was not found on this server.
Apache/2.4.52 (Ubuntu) Server at arborator.ilpga.fr Port 443

Will this problem be fixed? 
Quick Edit is amazingly good to edit conllu files and add colours!

**Comment by kimgerdes** [comment]
it has moved to arborator.elizia.net
indeed, a redirect should be put into place...
sorry about that
