### ISSUE TITLE
incoherence in match objects

### ISSUE THREAD

**Issue by kimgerdes** [Arborator/arborator-frontend#15]
the returned match object are different in standard grew search and in the match objects returned with the relation table

```javascript
// matches in standard query table:"kimgerdes":{"edges":[],"nodes":["2"]}
// in relation table: "kimgerdes":{"edges":{"e":{"source":"ROOT","label":"root","target":"2"}}
if (!Array.isArray(usermatch.nodes)) usermatch = {'nodes':[usermatch.edges.e.target],'edges':[]}
```

the last line repairs that before opening the graph to avoid errors, but maybe it's better to do that in flask?

**Comment by kirianguiller** [comment]
@kimgerdes , @bguil , is it still this behavior ? Otherwise, we can close the issue
