### ISSUE TITLE
Change the visbility icons

### ISSUE THREAD

**Issue by khansadaoudi** [Arborator/arborator-frontend#150]
**feature related to the problem**

Green and purple locks don't express the visibility mode (green lock doesn't mean that the project is public)
 
**Describe the solution**

The icons should communicate an information

**Comment by kirianguiller** [comment]
Here is the new visibility icons (refactored in ProjectIcons.vue file) : 
![image](https://user-images.githubusercontent.com/35531073/220208415-fd12eaaa-4e33-434a-b7fc-45701ac7e622.png)
![image](https://user-images.githubusercontent.com/35531073/220208434-c4072efc-c99e-4ef5-86ee-6df2b8dabac1.png)
