### ISSUE TITLE
Show error message when no file is selected

### ISSUE THREAD

**Issue by khansadaoudi** [Arborator/arborator-frontend#156]
**Feature related to the problem**

If the user doesn't select a file and click on upload, it shows success message 

**Describe the solution**

Get error message no file is selected

**Comment by bguil** [comment]
If the modal "Select one or multiple conll files" does not contains a  least a file, the upload button should be disabled.

In general, whenever possible, I prefer that a button is disabled when it is not useful instead of having an error after clicking the button.
