### ISSUE TITLE
Fix the problem of black backgrounds in dark mode

### ISSUE THREAD

**Issue by khansadaoudi** [Arborator/arborator-frontend#163]

**Comment by kirianguiller** [comment]
I've just fixed this problem. 
Altough @khansadaoudi suggested she could do it, the logic for handling the dark mode for the trees is outside Arborator-frontend and is located in this repo : https://github.com/kirianguiller/DependencyTreeJS

As I've made the repo and the documentation was still missing, I decided to add the documentation as well as the logic for dark/light mode :).

@khansadaoudi, if you don't like the colors, you can either :
- suggest new coloring  in the repo : https://github.com/kirianguiller/DependencyTreeJS
 via a Pull Request 
 - defined your own coloring in Arborator, I can show you how to do

**Comment by khansadaoudi** [comment]
@kirianguiller I have just opened arborator from my phone i didn't have this problem with the dark mode

**Comment by kirianguiller** [comment]
On both santiago's and my machine, the problem persits after refresh. I will try to debug it now.

**Comment by khansadaoudi** [comment]
@kirianguiller now i'm having problem with light mode 
![image](https://github.com/Arborator/arborator-frontend/assets/50585493/6632c71b-2ba3-4ec7-a0bb-6d04f5bc7eb8)
