### ISSUE TITLE
Review Metadata modal

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#167]
Expected modification in red on the screenshot:

<img width="632" alt="Screenshot 2022-11-08 at 14 51 28" src="https://user-images.githubusercontent.com/687155/200583003-2b7e66ff-7183-4163-b610-0c16a049069b.png">

**Comment by kirianguiller** [comment]
Thank you @khansadaoudi for fixing this issue. It seems that it's working fine now. I'm closing the issue !
