### ISSUE TITLE
cannot upload conllu files

### ISSUE THREAD

**Issue by vistamou** [Arborator/arborator-frontend#169]
Hello,

Although I'm logged in, it is not possible to upload any conllu files,
it throws constantly an error.

Could you please fix this?

Thanks :)

**Comment by bguil** [comment]
I observe the same problem.

@gguibon, @kimgerdes, @kirianguiller: I don't see any request on the Grew Backend. I suppose that the problem in the the Flask part. Can you have a look?

**Comment by kirianguiller** [comment]
Sorry, I've just seen this (critical) issue. I'm checking rn.

**Comment by kirianguiller** [comment]
Fixed with https://github.com/Arborator/arborator-backend/commit/e601b415b228b32aa22096d6eb641db20abc060d 

Thanks !
