### ISSUE TITLE
requête qui ne fonctionne pas 

### ISSUE THREAD

**Issue by maigida** [Arborator/arborator-frontend#17]
la requête suivante qui fonctionne correctement dans GREW ne fonctionne pas dans GREW-Arborator:
pattern { N [form="kuma", Gloss="too"] }

Le trait "Gloss" (ajouté dans les Misc du naija) n'est pas reconnu.

**Comment by bguil** [comment]
Les versions de la bibliothèque Grew utilisé dans **Grew-match** et dans **Arborator-Grew** sont (temporairement) différente:
Pour rechercher la `fom="kuma"` et Gloss="too"`, il faut écrire:

 1. dans **Grew-match**: `pattern { N [form="kuma", Gloss="too"] }`
 2. dans **Arborator-Grew**: `pattern { N [form="kuma", _MISC_Gloss="too"] }`

Un exemple dans **Arborator-Grew** [ici](https://arboratorgrew.ilpga.fr/#/projects/NAIJA_Master_29.05/WAZL_08_Edewor-Lifestory_MG?q=Z2xvYmFsIHsgc2VudF9pZCA9ICJXQVpMXzA4X0VkZXdvci1MaWZlc3TEoHlfTUdfXzMiIH0KcGF0dGVybsSGIE4gW2bEoG09Ii8vIiwgxKtJU0NfR8SBc3M9UFVOQ1RdxLIKCg==).

La version 1 sera bientôt disponible dans les deux outils.

**Comment by marinecourtin** [comment]
Merci Bruno pour la réponse
