### ISSUE TITLE
URGENT problem with tree display

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#173]
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/23051796/201705558-f857e222-717e-4c87-94b1-b132b7d0879d.png">

**Comment by kirianguiller** [comment]
Fixed, sorry for the inconvenience.
It was related to the recent DARK MODE added feature. I invite you all to try the dark mode (click on the moon icon in the top-right of the window :) )
