### ISSUE TITLE
Missing Dependency relation rel

### ISSUE THREAD

**Issue by NeldaKote** [Arborator/arborator-frontend#175]
![dep](https://user-images.githubusercontent.com/35638096/202302179-76698482-a53f-4806-9da5-4dc2810f96c9.JPG)
When creating a dependency relation on the field rel, there are missing options for the rel tags of UD.

**Comment by bguil** [comment]
A JSON configuration file is available [here](https://gist.github.com/bguil/4b12560ec87ae4292f668916b7e4f858) fro UD (see #133).

In the project conf page, a button **Reset to UD** should be added next to the one **Reset to SUD**.

@NeldaKote: in the meantime, you can just copy/paste this JSON file into your project configuration.
