### ISSUE TITLE
Encoding format 

### ISSUE THREAD

**Issue by RZiane** [Arborator/arborator-frontend#177]
Hi,

When trying to upload a new file, I got the error "Error 500" which was not very telling. 
I finally realized that it was related to the encoding of my file which was in ANSI. In utf-8, it works as usual. 

I don't know if it's a feature or an error but it would be nice to have a more detailed message if only certain encodings are accepted.

**Comment by khansadaoudi** [comment]
Thanks for reporting this issue, the supported encoding format is UTF-8 . We added error message  in this commit [b88d007](https://github.com/Arborator/arborator-frontend/commit/b88d0077e68004958d52b6de36e1535171bb7d3a) for better understanding.

Thanks
