### ISSUE TITLE
Conll view

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#18]
In Conll view:

- [x] the symbol `#` starts comment only at the beginning of a line (see screenshot)
- [ ] strange to have an "disabled" button OK 

<img width="1118" alt="Screenshot 2020-05-31 at 07 34 50" src="https://user-images.githubusercontent.com/687155/83345253-54c21b00-a311-11ea-9ff0-cb9f6e8678ac.png">

**Comment by kimgerdes** [comment]
yes, the grammar of the codemirror has to be changed to take # into account only in the beginning of the line. can you do that @gguibon ?
the OK button becomes enabled as soon as you modify the conll. maybe it should be made clearer that you can not only view the conll but also modify it direclty.

**Comment by marinecourtin** [comment]
The grammar was changed to take only # into account for sentence comments
