### ISSUE TITLE
Dictionary Edit

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#186]
@kimgerdes @kirianguiller @bguil 

Using the dictionary editor on a whole project, with multiple files creates havoc. 
The files of the project get mashed up with bits of the different files being inserted in each other. 

Not a pretty sight!

**Comment by bguil** [comment]
@B-CARON: Sorry for this! 
Can you tell what you have done exactly?
 - which project?
 - when have you observed the problem?
 - you have used the "Apply rules" button?

**Comment by B-CARON** [comment]
Je réponds personnellement en détail par captures d’écrans.   « Get lexicon of my trees »   Sort on lemma  Je sélectionne et modifie les entrées dans le menu popup  Je sélectionne entrées modifiées et je génères les règles Je teste les règles   Je clique sur le bouton « Apply rules »    J’ai le message « CONLL saved »  Si j’ouvre le fichier CONV_01 , je constate que les 3 fichiers CONV_01, CONV_02 et CONV_03 ont été concaténés…   Dans le fichier CONV_02, j’ai les fichiers 02 et 03 à la suite.  CONV_03 est intact.  Quelquefois, CONV_03 est touché également…   Voilà B.  Bernard Caron57, avenue d’Italie75013 PARIS06 63 68 15 19 De : Bruno GuillaumeEnvoyé le :jeudi 26 janvier 2023 13:58À : Arborator/arborator-frontendCc : B-CARON; MentionObjet :Re: [Arborator/arborator-frontend] Dictionary Edit (Issue ***@***.***: Sorry for this!Can you tell what you have done exactly?which project?when have you observed the problem?you have used the "Apply rules" button?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by B-CARON** [comment]
PS : j’ai remis les fichiers d’origine dans mon projet… Bernard Caron57, avenue d’Italie75013 PARIS06 63 68 15 19 De : Bruno GuillaumeEnvoyé le :jeudi 26 janvier 2023 13:58Objet :Re: [Arborator/arborator-frontend] Dictionary Edit (Issue ***@***.***: Sorry for this!Can you tell what you have done exactly?which project?when have you observed the problem?you have used the "Apply rules" button?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by khansadaoudi** [comment]
Hello @B-CARON ,
Thank you for reporting this issue I will try to reproduce it and see how to fix it asap.

**Comment by khansadaoudi** [comment]
Fixed in this commit [db24ace](https://github.com/Arborator/arborator-backend/commit/db24ace445ca56e52d21e1c1507bb20f6a8daaf2)
