### ISSUE TITLE
Punctuation annotation

### ISSUE THREAD

**Issue by RZiane** [Arborator/arborator-frontend#187]
Hi everyone, 

A long time ago, we talk about dependency relation for punctuation. 
It could be annotate automatically if all the dependency structure is already annotated. 
Did anyone know if someone developed it. 

And this would be great if it could be integrated to arborator.

**Comment by sylvainkahane** [comment]
I agree ! Especially for spoken corpora, where we use almost only simple punctuations. It is more problematic with double punctuations, such as (…) or "…". The tool should ask us our list of double punctuation pairs.

**Comment by sylvainkahane** [comment]
Punctuations are attached to the foot of roof in most cases. There are exceptions.
First, double punctuations: one is attached to the foot of its roof, but not the other one. This can be solved if we know that such a punctuation is linked to another punctuation and must have the same governor.
Second, reported speech: The final punctuation of a reported speech is attached to the root of the reported speech, and therefore is not attached to the foot of its root, which is the root of the sentence. In spoken corpora, we have added a feature Reported=Yes on the root of a reported speech, which can help to automatically find the right attachment, but the rule will not be trivial.

**Comment by kirianguiller** [comment]
Yes. The recent parsers are really good for annotating the punctuation, as you can see in this sample : https://arboratorgrew.elizia.net/#/projects/chinese_grammar_wiki_morphSUD/chinese-wiki_corpus.B2.mSUD  (look for kirparser10, which is a parser that was trained on 250 gold sentences for 10 epochs (around 30 seconds of training), and it's almost always right for the punctuation.
As we are working on making the automatic parsing a more central and easier step of arboratorgrew, it might be enough for your punctuation needs (for reported speech etc). Especially that the punctuation parsing is the easiest part for a parser to learn.

Let's close the issue and reopen it again if we realize the parsers are not able to train on punctuation!
