### ISSUE TITLE
Grew Internal error

### ISSUE THREAD

**Issue by NeldaKote** [Arborator/arborator-frontend#188]
Hello, 

We are facing the following error. I can not see all the sample files that I have in this project anymore. In one of the sentences, I added a new feature at Meta but I specified only the value and not the name of the feature. Now I cannot make any changes since the file is not any more accessible.

![image](https://user-images.githubusercontent.com/35638096/215494796-64fb5a36-cc9d-408a-9fc9-a171b2135862.png)

**Comment by NeldaKote** [comment]
The same error occurs. I don't have access.

**Comment by NeldaKote** [comment]
I just recheck it, and now is ok. Thank you.

**Comment by bguil** [comment]
Ok, fine. I let the issue open.
We will try to reproduce the problem to avoid similar future problem.
