### ISSUE TITLE
Logic of "Apply rules"

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#190]
After some rules applications (`Try Rules` button), the new trees produced are displayed and there is a button `APPLY RULES`.
Currently, this button make changes on trees from other users, which is not the wanted behaviour.

I think that `APPLY RULES` should only change "my trees".
For each sentence where the `APPLY RULES` produces a new tree, two cases:
 - I don't have a tree for this sentence, the tree produced by the rules is added as my tree
 - I already have a tree for this sentence, it is replaced by the new tree produced by the rules.

In order to know on which trees, the rules should be applied, I suggest that, when we select the `Grew` button, we have a secondary choice (like for tables) with:

  - "Only my trees"
  - "My tree, filled with more recent ones"
  - "Most recent trees"
  - ~~"All trees"~~ &rarr; this case is problematic for `APPLY RULES`, because, for the same sentence there can be two annotations form two users $A$ and $B$ and the `APPLY RULES` may produce two new annotations $A'$ and $B'$ and we don't know which one to choose as the result of the application.

**Comment by sylvainkahane** [comment]
I agree but I don't understand the second choice you propose "My tree, filled with more recent ones".

**Comment by kirianguiller** [comment]
I think the main problem of apply rules is that we search for trees that suit the pattern both in the trees of the user that is doing the rewrite, and in the trees of other users.

The tricky part is : what tree do we change when the user doesn't have a tree but many other users do have a tree for a sentence ? I think we should only modify the last one (after copying it for the user). 

But I find this a bit weird, it would "import" a lot of new trees for the user. Maybe we just want to apply rules for trees of the user only ? So we could rename the button : "apply rules for all my trees". It would be clear for the user, and the behavior would be simple ? 

In any case, I'm now adding the restriction, so it only rewrite conll of a user, to avoid people editing the trees of other people.

**Comment by kirianguiller** [comment]
@khansadaoudi  fixed it in 53d0490. Some changes were added in previous commit too for better logging of the effect of the rules.

Now it should behave as @bguil suggested in original message.
Closing the issue
