### ISSUE TITLE
DEPS: Enhanced dependency graph in the form of a list of head-deprel pairs.

### ISSUE THREAD

**Issue by VasilisTz1** [Arborator/arborator-frontend#192]
Hello,

I was wondering if ArboratorGrew supports DEPS (The 9th column according to the CoNNL format)...

Thank you in advance!

**Comment by bguil** [comment]
ArboratorGrew does not currently support Enhanced dependencies encoded in columns **DEPS**.
This feature is not planed on a short term, sorry!
