### ISSUE TITLE
Primary Color (purple) not suitable when in dark mode

### ISSUE THREAD

**Issue by kirianguiller** [Arborator/arborator-frontend#195]
The default primary color for dark mode is `#4a2769`. This is too dark on dark background which make a lot of the UI unreadable. I tried to find a way to change the primary for dark mode only in quasar.variables.scss, but it didn't work as expected.

Here are some examples : 
![image](https://user-images.githubusercontent.com/35531073/219948967-9d1fe37c-1ee2-4d21-b323-921041c65309.png)

![image](https://user-images.githubusercontent.com/35531073/219948999-f19782bb-73bc-4e81-8c77-03efbf346518.png)

**Comment by kirianguiller** [comment]
another place where it make the components unusable (grew dialog) : 
![image](https://user-images.githubusercontent.com/35531073/220192863-6f77bde1-34a8-4d88-844d-fd28e2eaafa7.png)

**Comment by khansadaoudi** [comment]
fixed in this commit [a854281](https://github.com/Arborator/arborator-frontend/commit/a854281c61333bafa985e0c5d046722dd56b9e05)
