### ISSUE TITLE
constrain rel and deprel

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#200]
Only some combinations of rel and deprel features are possible, for instance `comp:obj` but not `subj:obj`. It would be nice to encode this in the SUD settings, in order to adapt the menu as soon as I select a rel or a deprel value. It will speed up and improve the manual annotation.
But the updating of the annotation settings will be more complex.

**Comment by khansadaoudi** [comment]
This proposition is mentioned also [here](https://github.com/Arborator/arborator-frontend/issues/272) so I will close this one
