### ISSUE TITLE
Tooltip on top of text prevents from reading it

### ISSUE THREAD

**Issue by gguibon** [Arborator/arborator-frontend#201]
The tool tip on the sentence in the treebank view, prevent from reading correctly the text.
It should have an offset towards the top.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/8986236/220371230-04c8b701-a22e-465d-8e6a-7fdbc0a288c2.png">

**Comment by kirianguiller** [comment]
Is it fixed @khansadaoudi  ? I'm closing the issue as you mentioned a fix commit.

**Comment by khansadaoudi** [comment]
Yes it's fixed
