### ISSUE TITLE
import plain text

### ISSUE THREAD

**Issue by santiagohy** [Arborator/arborator-frontend#203]
For the moment, Arborator only allows us to load conll files. It will be nice to be able to import plain text files. It could read the input file in a simple way: one sentence per line, considering that a token is what is found between two spaces.

**Comment by bguil** [comment]
I think that this is really easy to implement with a few lines of code. 
Maybe the question is to decide how are chosen the `sent_id`.
 
I propose to add a switch (between Conll or text) in the "import sample" between Conll or text (or just using file extension)
and to use the sample name as the base for building `sent_id` like:
 - `foo_0001`
 - `foo_0002`
 - …

if the sample is name `foo` (the number of digit can be adapted to the size of the sample).

**Comment by khansadaoudi** [comment]
This feature is added in this commit [99db7af](https://github.com/Arborator/arborator-frontend/commit/99db7afbd92eccd8d1fa16eb208a4e04e3326e72)
