### ISSUE TITLE
Info sur le nombre d'arbres par utilisateur (getSamples)

### ISSUE THREAD

**Issue by kirianguiller** [Arborator/arborator-frontend#206]
@bguil , est-ce que tu penses qu'il est possible d'obtenir, dans le getSamples service (https://grew.fr/usage/grew_server/#the-getsamples-service), le nombre d'arbres par utilisateur. Cela serait utile pour deux raisons :
- connaitre, depuis la page projet, le nombre d'arbres annotés par chacun des utilisateurs pour chacun des samples (on pourrait le mettre en tooltip du nom de chaque utilisateur, ou bien ajouter le nombre avant le nom de chaque utilisateur)
- connaitre le nombre de phrases qui seront parsées par le parseur lors de la phase de sélection des paramètres du parseur (puisqu'il est désormais possible de ne lancer le parseur que sur un des user_id).

Penses-tu que cela est possible d'un point de vue backend ? Ou bien ça rajouterait de la complexité à l'algo actuel (itération sur chacun des arbres) ?

**Comment by bguil** [comment]
Sans doute possible assez facilement, je regarde rapidement.

**Comment by bguil** [comment]
C'est disponible sur le serveur de dev. Voir [aa8e97a5](https://gitlab.inria.fr/grew/grew_server/-/commit/aa8e97a5c4b4a1f0cecd429f202f67098b999758) et la [doc](https://grew.fr/usage/grew_server/#dev).

**Comment by kirianguiller** [comment]
Super. I will add a branch that take into account this new behavior of getSamples
