### ISSUE TITLE
Grew internal error

### ISSUE THREAD

**Issue by Alba10** [Arborator/arborator-frontend#207]
Hi,
We are getting the following error while trying to open one of our projects. It is not possible to access any of the files in the project.

![Error](https://user-images.githubusercontent.com/13187925/221422838-03b45367-3942-4c39-a64d-5e18a2728d80.jpeg)

**Comment by bguil** [comment]
Hi @Alba10, 

I'm really sorry for the problem you have with ArboratorGrew!

In the current data of your project, there are many tokens where the feature values are empty. I don't understand how this can happen and I didn't manage to reproduce the problem in one of my project.

Some lines are like this one:

```
9	u	ata	PRON	_	Case=|Gender=|Number=|Person=|PronType=Prs	_	_	_	_
```
With features `Case`, `Gender`… with empty values.

Unfortunately, I'm not able to fix this in the data. I see several scenarii to helps you recover the data: 
 - I send you the list of problematic lines (form, lemma, upos, features) and you tell me what are the right feature values. There are 215 cases! For instance:
```
u	ata	PRON	_	Case=|Gender=|Number=|Person=|PronType=Prs
u	ato	DET	_	Case=|Gender=|Number=|PronType=Art
u	ato	PRON	_	Case=|Gender=|Number=|Person=|PronType=Prs
u	u	DET	_	Case=|Gender=|Number=|PronType=Art
u	u	PRON	_	Case=Dat|Gender=|Number=Plur|Person=3|PronType=Prs
u	u	PRON	_	Case=|Gender=|Number=|Person=|PronType=Prs
``` 
 - I can replace missing value by fake values `TODO` that you can fix later, but there are many such problems
 - I send you the corrupted files, if you known how to fix them with a script

**Comment by Alba10** [comment]
Hi @bguil,
Thank you for the fast response. 

If it easy for you please replace the missing values with a fake value, since our annotators are going to check each of them. If it requires a lot of work from your side, please send us the corrupted file and we will try to fix ourselves.

**Comment by bguil** [comment]
I've replaced missing feature values by the fake value `TODO`. You should be able to open your project again.

Sorry for the inconvenience, I will try to understand the issue to prevent future problems.

**Comment by Alba10** [comment]
Thank you! It is ok now.

**Comment by kirianguiller** [comment]
@Alba10 , could you provide a link to the original conlls you uploaded to arboratorgrew ? It will help us debugging the app. Thanks !
