### ISSUE TITLE
sauvegarde de modifs

### ISSUE THREAD

**Issue by maigida** [Arborator/arborator-frontend#21]
après une recherche GREW, affichage d'un des arbres listés, j'ai fait une modification dans cet arbre sans pouvoir sauvegarder la modification. Fausse-manip? Pas encore implémenté?

**Comment by marinecourtin** [comment]
Bonne manip :), on a repéré ce bug aussi, il est en train d'être fixé. J'envoie un mail quand ça serait fait

**Comment by sylvainkahane** [comment]
Je commence à travailler sur le projet ParisStories. Je suis logué avec mon compte  github. Je fais une modifs mais je ne peux pas sauver. (Petit triangle rouge apparait dans le coin de l'écran)

**Comment by kimgerdes** [comment]
c'est réparé. on le met en prod sous peu.
