### ISSUE TITLE
Several problems relative to file upload

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#212]
Related to #211, I've made some tests. There are a several problems:

1. It is possible to upload several times data with the same filename. The second time, already existing `sent_id` are replaced by the new data and previous annotations are lost; non existing `sent_id` are added to the previous ones. I propose to forbid the uploading of a file if a sample of the same name already exists.
2. If the file fails to upload due to format errors, the sample is created anyway with 0 sentences. In this case, the sample must not be created.
3. If the file contains several sentences with the same `sent_id`, only one of the sentence is kept. This should bring an error.
4. If the field `FEATS` contains several declarations of the same feature, only one is kept, without any error or warning (example below). NB: Grew does not accept this declaration, the problem is on the Flask side.

```conllu
# sent_id = test_features
1	tok1	_	NOUN	_	Number=Sing|Number=Plur	_	_	_	_
2	tok2	_	NOUN	_	Number=Plur|Number=Sing	_	_	_	_
```

**Comment by kirianguiller** [comment]
@bguil Do we want to allow to upload a file that already exist , but for different users ?
For instance, sentence_1 already has an annotation from annotator_1. Can I upload a file for this sample with an annotation of sentence_1 from annotator_2 ?
I think we want to allow this. It was the main way to add sentences from parsers, which we maybe not need anymore now that we have our own parsers included in ArboratorGrew ?

**Comment by bguil** [comment]
I agree that this is a usecase we should take into account. Ok for allow uploading in an already existing sample.
We just need a sensible level of warning to prevent bad usage.

I suggest that, before saving, we compute the intersection of the set of `user_id` in the new file and the set of `user_id` in already existing sample.
 - if the intersection is empty: no danger, upload directly
 - else, add a warning step with a message "You are uploading data for users `xxx` and `yyy` which have trees in the sample. The new trees will erase the previous ones if any. Do you want to proceed?"

**Comment by B-CARON** [comment]
As Arboretor is currently working you can upload an already existing file
but the original file is crushed without backing up. Personally I find this
very convenient when updating files modified in another program, i.e.
notepad++

Le sam. 15 avr. 2023, 09:35, Bruno Guillaume ***@***.***> a
écrit :

**Comment by kirianguiller** [comment]
@B-CARON , I'm not sure I understood well. You are saying that being able to rewrite trees by uploading samples is convenient ? or the contrary ?

**Comment by kirianguiller** [comment]
In the backend commit https://github.com/Arborator/arborator-backend/commit/b860c4ff4fd588f0b2758a03abecf62475ee79f2 , I just fixed : 
>     3. If the file contains several sentences with the same `sent_id`, only one of the sentence is kept. This should bring an error.

Now, the backend return an error message to the frontend in case of a file with format error (wrong number of columns, duplicated feats/misc/deps and some other basic format errors). 
It will not return all the errors of the conll, but only the first error it finds in every line. 
For instance, if a sentence has one error for token 1, and one error for token 2, it will display both errors. But if token 1 has 2 errors (i.e. two feats key both have duplication), it will only display the first it find.

Does grew-server would return all errors ? If so, maybe grew could have an endpoint that would just check the sanity of a conll (maybe it exists already). So in arborator-flask, when a user wants to upload a conll, we would : 
- check the conll with grew server
- if it's fine, modify/add the user ids and the timestamp ; if it's not fine, return the full error to the client and show the errors logs in a clearer way that currently
- save the conlls in grew server
