### ISSUE TITLE
Unusable error message

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#214]
When I try to upload a corrupted file (with a line with 9 column instead of 10), I have only `Internal Server Error error 500` and no more information.

A few weeks ago, a more useful message was avalaible with the line number. Can we have it again?

**Comment by kirianguiller** [comment]
fixed in https://github.com/Arborator/arborator-backend/commit/b860c4ff4fd588f0b2758a03abecf62475ee79f2
