### ISSUE TITLE
Optimize grew loop requests

### ISSUE THREAD

**Issue by kirianguiller** [Arborator/arborator-frontend#215]
It would be nice to go in the backend (flask) code and search for all loop requests (sentence wise, like saveGraph or deleteGraph) and see with @bguil if a bulk endpoint that does the same already exist or not. If not, @bguil could make some which would fasten the experience for the user by a large factor.

**Comment by bguil** [comment]
The following new services are available in DEV (see links for doc):
- [`newSamples`](https://grew.fr/usage/grew_server/#newsamples) 
- [`eraseSamples`](https://grew.fr/usage/grew_server/#erasesamples) 
- [`eraseGraphs`](https://grew.fr/usage/grew_server/#erasegraphs)
- [`saveGraphs`](https://grew.fr/usage/grew_server/#savegraphs)
- [`applyPackage`](https://grew.fr/usage/grew_server/#applypackage)
