### ISSUE TITLE
better exporting UX

### ISSUE THREAD

**Issue by kirianguiller** [Arborator/arborator-frontend#225]
We need a better exporting UX. Indeed, when exporting, we don't want the current structures of the files which is 
-- /folder
---- sample1.user_1.conllu
---- sample1.user_2.conllu
---- sample1.last.conllu
---- sample2.user_1.conllu 
---- sample2.user_2.conllu
---- sample2.last.conllu

instead, we want something like :
-- /folder
---- /user_1
------ sample1.conllu
------ sample2.conllu
---- /user_2
------ sample1.conllu
------ sample2.conllu
---- /last
------ sample1.conllu
------ sample2.conllu

Indeed, the current structure is a real nightmare, that force the users to rename the files if they want to import it again in arborator or any other projects

**Comment by kirianguiller** [comment]
It is a really important improvement (more than tags), so I add it to the milestone 2.1

**Comment by khansadaoudi** [comment]
it's working for me what did you do exactly
