### ISSUE TITLE
Show_Divergence feature is lacking two things

### ISSUE THREAD

**Issue by kirianguiller** [Arborator/arborator-frontend#228]
After some testing, it seems that the Show_Divergence feature is lacking two things (let me know if I'm wrong) : 
- it is not possible to only show the diff if a deprel is different. We can't "only select" the deprel feature for selecting the diffs
- if I'm annotator_A, it is not possible for me to see the diffs between annotator_B and annotator_C only (and not with me). This option is important as it's useful to see : the diffs between annotators if I'm a validator ; the diffs between different parsers output. The UI should allow to select a set of annotator in the project, oneself included, and only enable the search if at least 2 annotators are selected.

Other than these little things, the UI/UX is really nice. This feature is game changing imo. Thank you @khansadaoudi  :)

**Comment by khansadaoudi** [comment]
Yes, you're right. I will take this into consideration
