### ISSUE TITLE
grew rewrite result page has sentences box that are not scrollable horizontally

### ISSUE THREAD

**Issue by kirianguiller** [Arborator/arborator-frontend#231]
grew rewrite result page has sentences box that are not scrollable horizontally. So if a sentence is long, we can't scroll to the right. 

This screenshot show such a case (I can't go more to the right): 
![image](https://github.com/Arborator/arborator-frontend/assets/35531073/688af718-0b56-4180-abd5-70892627916d)

**Comment by khansadaoudi** [comment]
Thanks @kirianguiller for reporting this issue I have just fixed it

**Comment by kirianguiller** [comment]
super. Thanks !
