### ISSUE TITLE
Display of the MISC.EXTPOS

### ISSUE THREAD

**Issue by LiYixuan727** [Arborator/arborator-frontend#233]
Hi,
I noticed that the MISC.EXTPOS is always not displayed even if we chose it as feature to be shown in the preference. 
It would be great if we could see it during annotating

**Comment by sylvainkahane** [comment]
Just a remark, the feature is spelled ExtPos.
You must add it in the JSon before, if it is not.

**Comment by khansadaoudi** [comment]
@LiYixuan727 Like what sylvain said you have to add this feature in your project config first

**Comment by LiYixuan727** [comment]
It works now.
Thank you!



Le jeu. 15 juin 2023 à 16:23, Sylvain Kahane ***@***.***> a
écrit :
