### ISSUE TITLE
When sentence is long, the UI buttons got out of the window 

### ISSUE THREAD

**Issue by kirianguiller** [Arborator/arborator-frontend#235]
When a sentence is long, all the UI buttons (save, etc) go out of scope on the right and we need to scroll horizontally to access them. Only the sentence itself (the tree) should be scrollable, not the UI. The buttons should be on screen no matter the size of the tree.

Here is an example : 
![image](https://github.com/Arborator/arborator-frontend/assets/35531073/e5dbb4c6-b6d2-4644-8f81-cabeccb233dd)

**Comment by khansadaoudi** [comment]
fixed by @kirianguiller in the new merge
