### ISSUE TITLE
Allow the display of additional metadata fields

### ISSUE THREAD

**Issue by Lguyogiro** [Arborator/arborator-frontend#239]
It looks like, by default, the `text` field is displayed above the tree while annotating. Is it possible to configure which metadata fields are displayed there? For example, it might be helpful to see a translation, or perhaps the original text (`text[orig]`) while annotating.

**Comment by bguil** [comment]
In the project settings (the gear button on the right of your project name in the main project page),
there is a "Shown Features" box in which you  can "Choose the features to be shown under each sentence".

<img width="605" alt="Screenshot 2023-07-01 at 21 56 51" src="https://github.com/Arborator/arborator-frontend/assets/687155/452dae0d-a2de-4ad4-bb19-4b099ebc6609">

**Comment by Lguyogiro** [comment]
Works, thank you!
