### ISSUE TITLE
choix d'une relation

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#24]
Je clique sur une relation, la fenêtre pop up s'ouvre.  Qq trucs inattendus:

1. Il y a une croix après le nom de la relation, j'imagine que ça sert  à effacer le nom de la relation mais quand je clique dessus le nom de la relation reste. Rien ne change au niveau de la fenêtre pop up.

2. Par contre quand je clique sur ok, la fenêtre pop up se referme et la dépendance a disparu et pas seulement le nom de la relation. C'est pas l'action que j'attendais intuitivement.

3. Si je choisi une autre relation, le nom de la relation reste le même mais quand je clique sur ok, a fenêtre pop up se referme et le nom de la relation a bien changé. C'est l'action que j'attendais mais ca m'aurait rassurer de le voir dans la fenêtre pop up aussi.

4. Pour les traits subrel et deep, même genre de pb, rien ne se passe dan la fenêtre pop up mais ca fait bien ce qui est attendu sur le conll. Dans ce cas on peut supprimer le trait sans que ça supprime la dépendance.

**Comment by gguibon** [comment]
Corrigé.
