### ISSUE TITLE
Tagging of Sentences / Mark as Completed

### ISSUE THREAD

**Issue by mr-martian** [Arborator/arborator-frontend#241]
I have a project where I have a set of machine-generated trees being reviewed by multiple people and I'd like to be able to track which sentences have been completed. If someone other than me is doing the reviewing, I can sort of get this by looking at the last editor, but in addition to reviewing sentences, I'm also running a bunch of consistency queries, so me being listed as having edited a sentence doesn't really help.

Would it be possible to have a mechanism for marking a sentence as completed? Or maybe a more general system putting tags on sentences (stored perhaps as `# tags = A, B, C`) so that I can explicitly track annotation progress?

**Comment by khansadaoudi** [comment]
This feature was added in the new branch that will be integrated soon
