### ISSUE TITLE
Running a rewrite rule does not update already open sentences

### ISSUE THREAD

**Issue by mr-martian** [Arborator/arborator-frontend#242]
If I run a rule that changes the arc label of a sentence I already had open, I have to reload the page to actually see the changed version.

**Comment by kirianguiller** [comment]
I'm reopening this issue as the behavior now is bad for the UX .

Indeed, after doing a rewrite rule, it will reload the full page which will close the grew search/rewrite window and thus remove the previously written rule. It can be annoying if we want to reaccess to this rewrite rule, or if we want to stay in grew rewrite window to do another rule.
