### ISSUE TITLE
github feature: do we want to handle multiple pull requests?

### ISSUE THREAD

**Issue by gguibon** [Arborator/arborator-frontend#248]
If I create a new pull request based on new changes, it says one already exists because the name is the same. Maybe we would want to override the last one to make it for a smooth user experience.

**Comment by khansadaoudi** [comment]
@gguibon  I fixed this issue and then I realized that the pull request that you have already opened will take en consideration the new changes that you committed so you don't have to override that pull request
so I will close this issue
