### ISSUE TITLE
Probleme d'enregistrement

### ISSUE THREAD

**Issue by maigida** [Arborator/arborator-frontend#25]
Impossible d'enregistrer les modifications pour les phrases très longues. Ex:
 WAZP_04_Ponzi-Scheme_MG__185 

# and dis morning < # if you dey di city of Port < # as I dey comot here now dey head straight to Presidential < # { me |c and di owner of Sahara Energy } < # { me |c and { di || eh di } owner of { Kilimanjaro |c and eh Market Square } } < # { me |c and di owners of eh # O Wilson Tea Mate Bread |c # and also Hilda Dokubo |c # and a lot of dem } now < we dey Presidential dis morning |c # and we dey talk on di Niger Delta CEO Summit //

**Comment by maigida** [comment]
Je répète ma demande: suite à une recherche, il est impossible de sauvegarder certaines phrases très longues. Ca veut dire qu'on perd quelqufois un long travail...
Exemple : https://arboratorgrew.ilpga.fr/#/projects/CONLL%3C%3EPRAAT(3)/projects/CONLL<>PRAAT(3)/WAZL_03_News-On-Gmns_MG/3/bernard.l.caron

**Comment by kimgerdes** [comment]
je ne peux pas reproduire ce problème.
j'ai pu modifier et enregistrer la phrase en question sans problème.
est-ce qu'il y a plusieurs phrases comme ça ? as-tu essayé avec un autre navigateur ?

**Comment by marinecourtin** [comment]
J'ai bien une erreur quand j'essaie :

![Capture d’écran de 2020-06-15 14-32-32](https://user-images.githubusercontent.com/28790155/84657808-29e0e500-af15-11ea-8f98-5314ee6d1c41.png)

**Comment by kimgerdes** [comment]
je viens de tester avec la même phrase qui se trouve maintenant https://arboratorgrew.ilpga.fr/#/projects/NAIJA_MASTER_01.06/WAZP_04_Ponzi-Scheme_MG/1/kmgrds
et j'arrive à modifier et enregistrer sans problème. j'imagine que la nouvelle version a bien résolu ce problème
