### ISSUE TITLE
Saving Query as Template

### ISSUE THREAD

**Issue by mr-martian** [Arborator/arborator-frontend#250]
Quite a few times while using the query and rewrite rule interface, I've found myself writing many slight variations of the same thing, such as "find 2 adjacent words with these properties where the second one doesn't have a head". Would it be possible to add an option to save a query so that it appears in the list of templates on the right hand side?

**Comment by khansadaoudi** [comment]
Hello @mr-martian,  
This option is available in the constructicon feature. 
- Click on the tree icon next tp the parser panel to open constructicon panel 
![Capture d’écran du 2023-07-10 10-18-19](https://github.com/Arborator/arborator-frontend/assets/50585493/9e27e864-ea4f-4508-b3cc-c7e31ab171b9)
- To save a query click on add new item
![Capture d’écran du 2023-07-10 10-17-55](https://github.com/Arborator/arborator-frontend/assets/50585493/34552a0d-006f-4819-a153-88c6d08fda6c)

**Comment by bguil** [comment]
It seems that tags are not really saved nor exported.

**Comment by mr-martian** [comment]
Excellent, thank you.
