### ISSUE TITLE
Exporting a corpus in .connlu

### ISSUE THREAD

**Issue by savary** [Arborator/arborator-frontend#254]
Hi,
We are crying to export [this corpus](https://arboratorgrew.elizia.net/#/projects/Cr%C3%A9oleHa%C3%AFtien/CorpusHaitien-1_1) in .conllu. The only way we can see is to open each sentence and click on "Get CoNLLU of this tree". Then we have to copy-paste the screen to an ascii file.

Is it possible to export the whole corpus at once?

Thanks, 

Agata

**Comment by khansadaoudi** [comment]
Hello @savary 
Yeah there is a way to export conll files
In the project screen you have to select a corpus and click on the cloud icon
![image](https://github.com/Arborator/arborator-frontend/assets/50585493/606067ad-f466-4c5e-8068-6f6272e9d2c0)
You get a dialog where you can choose which trees to export 
![image](https://github.com/Arborator/arborator-frontend/assets/50585493/14947592-eea4-4411-ae24-9dbc966de4df)
The conll files will be exported in Zip archive

**Comment by savary** [comment]
Works for me! Thank you!

**Comment by khansadaoudi** [comment]
By the way  ArboratorGrew documentation is available from [here](https://arborator.github.io/arborator-documentation/#/)
