### ISSUE TITLE
Remember Synchronized Repository

### ISSUE THREAD

**Issue by mr-martian** [Arborator/arborator-frontend#256]
Any time I reload the page, I have to go through the process of synchronizing with github again. Would it be possible for a project to be permanently associated with a repository?

**Comment by khansadaoudi** [comment]
@mr-martian You don't have to go through the process again, it's a frontend problem when you reload the project page the github options button disappears. But your project is always synchronized with your repository. To show the button again you can simply return back to project hub page and the reopen your project.
Meanwhie you will try to fix this problem asap thank you

**Comment by mr-martian** [comment]
Possibly related issue: the number of changes to be committed doesn't update and thus I also have to reload to push if, for example, I've been working entirely from the search page and haven't gone into any of the samples and thus the number of changes is still 0.

**Comment by khansadaoudi** [comment]
@mr-martian the second problem is solved now. The number of changes is updated automatically.
