### ISSUE TITLE
duplication of sentences after parsing

### ISSUE THREAD

**Issue by LiYixuan727** [Arborator/arborator-frontend#258]
Hello,

I encountered an issue with the parsing of the treebank [ALL_claims11_ch_new_upos_spacy](https://arboratorgrew.elizia.net/#/projects/SUD%20Chinese/ALL_claims11_ch_new_upos_spacy) in SUD Chinese project.

Although the parsing process itself is functioning correctly, I noticed that the results are being saved with a different ID suffix. This has led to the duplication of the number of sentences, increasing from 167 to 334.
For instance, the original sentence is labelled as 1690030817.174349-810321_00001, while the parsed tree is saved as 1690030953.533326-810322_00001.

Furthermore, I have observed that all sentences in the treebank disappear after a certain period of time.

Thank you in advance for your help.

**Comment by khansadaoudi** [comment]
Hello, 
The problem is that the parser has created new sentences without `# sent_id = `  and that's why the sentences disappear after certain moment. For the parser problem I still can't define it, can you provide us more details to see how can we reproduce it.
