### ISSUE TITLE
ascenseur inaccessible

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#26]
Le bouton d'ascenseur (redessiné en bleu sur la copie d'écran) peut être derrière les 2 boutons ronds et inaccessible.

![Image 10-06-2020 at 08 52](https://user-images.githubusercontent.com/687155/84236448-ee4eb100-aaf7-11ea-8858-ef78ab6e88cf.jpg)

**Comment by kimgerdes** [comment]
réparé. mise en prod sous peu.
