### ISSUE TITLE
[Feature request]: sample origin of query results

### ISSUE THREAD

**Issue by kimgerdes** [Arborator/arborator-frontend#264]
### Is there already a feature request for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

When Grewing on the page of a project, I want to know from which sample the results come from.

### Suggest a solution

- Cluster the results by sample
- Or put the sample name before the text id of each resulting sentence.

**Comment by khansadaoudi** [comment]
fixed in the last commit
