### ISSUE TITLE
[Bug]: upload fails

### ISSUE THREAD

**Issue by kimgerdes** [Arborator/arborator-frontend#269]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

sometimes when uploading a conll I get this strange error:
![image](https://github.com/Arborator/arborator-frontend/assets/12749873/c5b1a144-2acf-4d09-936f-291e36631fd8)
this can be resolved when I add any custom User ID.

### Steps To Reproduce

Here's a file where this happened, but I don't know if it's actually related to the file.
[2.conllu.zip](https://github.com/Arborator/arborator-frontend/files/12284878/2.conllu.zip)

### Project name

ESSLLI_2023_Treebanks

**Comment by khansadaoudi** [comment]
@kimgerdes this error is raised when you upload the file without the userId by default custom userId input is filled by your username.
I will try to disable the upload button when the userId input is empty in order to avoid sending files without userId

**Comment by kimgerdes** [comment]
or maybe pre-fill by default with the user's user id to avoid problems?
