### ISSUE TITLE
[Feature request]: change home page to project page

### ISSUE THREAD

**Issue by kimgerdes** [Arborator/arborator-frontend#275]
### Is there already a feature request for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

a user of arboratorGrew does not want to go through the extra click of the home page every single time.

### Suggest a solution

The home page of arborator grew should point directly to the project page and the logo link on top should point there too.
the current home page should be accessible as an info page under a corresponding button/icon.

**Comment by khansadaoudi** [comment]
fixed in [this commit](https://github.com/Arborator/arborator-backend/commit/a589ec1bb62b525ad67439e7c7540e8bb0df5e73)

**Comment by kimgerdes** [comment]
it's not yet pushed into production it seems. Can you do that?

**Comment by khansadaoudi** [comment]
No it's already pushed in prod

**Comment by kimgerdes** [comment]
when logged in and on a sample page 
![image](https://github.com/Arborator/arborator-frontend/assets/12749873/0e27178a-9a6a-409f-b8e2-b43c99cf066b)
and clicking on the ArboratorGrew icon, I land here:
![image](https://github.com/Arborator/arborator-frontend/assets/12749873/4d8f2653-fe0b-450d-a510-52d3097492ba)
