### ISSUE TITLE
Question: Alternate Tree Interface

### ISSUE THREAD

**Issue by mr-martian** [Arborator/arborator-frontend#276]
Hello,

We, the developers of [UDAnnotatrix](https://github.com/jonorthwash/ud-annotatrix/), were curious about the possibility of using Annotatrix as an alternative frontend to ArboratorGrew, since the server protocol already supports most of the features that we intended to add but some members of our team strongly dislike the editing process in Arborator.

This could take the form of either creating an alternative to this repository or a pull request adding the option to switch just the tree-editing window to a version of Annotatrix.

Thus our question is, would you approve of such an endeavor and, if so, is there any documentation that we should be aware of as we begin the process?

ping: @jonorthwash @ftyers @lguyogiro

**Comment by kimgerdes** [comment]
Hello Daniel, all, @jonorthwash @ftyers @Lguyogiro
we'd be excited to help you to add an alternative editing window to the current AG look and feel. Personally, I'd also love more keyboard shortcuts and multi-line views. Having Annotatrix's options on top of or integrated into AG would be an important improvement of the current tool.

We currently have a full-time developer, @khansadaoudi, who could certainly assist you, although we don't have great documentation of the code for the time being. Maybe we could schedule a meeting soon to see how to get that endeavor off the ground?

**Comment by mr-martian** [comment]
Excellent. I think the easiest way to discuss scheduling for a meeting might be for you to email me (address in my profile).
