### ISSUE TITLE
[Bug]: Failed to open tree sample

### ISSUE THREAD

**Issue by s-herrera** [Arborator/arborator-frontend#279]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get a 'Server Internal Error 500' every time I try to open my trees and I'm redirected to an empty website or to a tree sample that's not part of my project. It's worth saying that I can download properly the annotated trees.
The only peculiarity I can think of in the my project is that I use custom annotation settings.

### Steps To Reproduce

1. Open the project
2. Go to the "l'education sentimentale" sample and open the sample of sentences
3. You get the error

### Project name

SyntaxeAlOuest2023

### Anything else?

![image](https://github.com/Arborator/arborator-frontend/assets/95502001/545c770e-b374-43d7-b288-7b29db444e56)

### What browsers are you seeing the problem on?

Firefox

**Comment by khansadaoudi** [comment]
Hello @s-herrera 
I have just debug the issue and I found that you have file format error in this line
`1	Il	lui	PRO	_	_	2	sujet	_	GroupeSynt=GN|ProNature=Personnel|GroupeSynt=GN` 
you have duplicate GroupeSynt key.

**Comment by s-herrera** [comment]
Oh, thank you. Sorry for the troubles. It would be nice to get an error message telling us which is the bug so any user can debug it and we don't have to bother you with it again. Thanks again!
