### ISSUE TITLE
Utilisation hors login

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#28]
Quand je ne suis pas connecté, je peux voir les arbres d'un projet public, les modifier et cliquer sur "Save this tree": les modifications ne sont pas sauvées mais cela ne produit aucune erreur. 
NB: browser = Brave

**Comment by marinecourtin** [comment]
Résolu en dev 1778b6ddf65790225896295b54b57941b1ba3ec0.
Je fermerai l'issue quand ce sera poussé sur le serveur.
