### ISSUE TITLE
[Feature request]: Support enhanced dependencies

### ISSUE THREAD

**Issue by Lguyogiro** [Arborator/arborator-frontend#280]
### Is there already a feature request for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

In a previous [issue](https://github.com/Arborator/arborator-frontend/issues/192)  (from February) it was stated that there were no short term plans to support enhanced dependencies. I wanted to resurface this request here to see if it might be something of interest. 

Enhanced dependencies are really valuable for linguistic analysis, in particular for things like noun-incorporation (see [https://aclanthology.org/2020.udw-1.22/](https://aclanthology.org/2020.udw-1.22/)). We currently have a number of projects that use this approach to annotation, but cannot annotate them in Arborator because the validator breaks on empty nodes that have enhanced dependencies.

### Suggest a solution

Ideally, full support of enhanced dependencies would be great. If this is too much to ask, at the very least might there be a way to allow uploading conll-u files with empty nodes without the validator throwing an error?

Thanks.

**Comment by ftyers** [comment]
We currently have a project on annotation for 5 languages of Mesoamerica, and need this to be able to handle noun incorporation in varieties of Nahuatl.
