### ISSUE TITLE
[Feature request]: rename a project

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#282]
### Is there already a feature request for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

Project names cannot be changed

**Comment by kimgerdes** [comment]
I failed to find this feature in the interface.
Is it hard to add the possibility of changing the name of a project in the project settings?

**Comment by kimgerdes** [comment]
Thanks for adding the renaming inside the project settings. it works great (except that the back button breaks as the URL disappears, but that's ok)
However, when using the right-click renaming feature on the project page, the project card does not change, and the link on the card points to the old project name, which causes a 500 error (why not a 404 btw?).
