### ISSUE TITLE
[Bug]: Suppression of a file

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#286]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cant' suppress a file from my project.

### Steps To Reproduce

1. I tried to suppress one file or several files together. 
2. The name of the project is asked and I write it. 
3. I confirm the suppression. 
4. The window closes, nothing happens, and I have no message saying if it has worked or not.

### What browsers are you seeing the problem on?

Firefox

**Comment by khansadaoudi** [comment]
I close this issue because it wasn't reported by other persons, if you still have it you can reopen the issue
