### ISSUE TITLE
[Bug/request]: selection of "rewrite"

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#289]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we use Grew, the default mode is "Search" and it is difficult to choose "Rewrite". Sometimes I have to click several times.

### Steps To Reproduce

I have several suggestions:

1. When we come back to Grew after applying a rewriting rule, it would be better to be again in the "Rewrite" mode.
2. When we click on Search with a rule, it could do as if I was in the Rewrite mode.
3. And vice versa, if I click on Rewrite with only a pattern, it could apply the Search mode.

### What browsers are you seeing the problem on?

Firefox

**Comment by sylvainkahane** [comment]
I still have this problem.
And I still ask for my 3 suggestions to be implemented.

Another suggestion: sometimes I wanted to apply a rule on the more recent trees, but I didn't see that "only my trees" was selected. As already suggested, the default mode, must "more recent trees".
But also the button should recall what we are doing: so replace "Try the rules" by "Try the rules on the more recent trees" or "Try the rule on my trees". Another solution could to put the selection of the trees near the "Try" button.

**Comment by sylvainkahane** [comment]
I still have the same problem: I have to click 4 times to switch from one mode to the other.

But about the switch from one mode to the other, I have some suggestions to do:
- [ ] when I open Grew, it must open on my last mode (now it opens in Search mode when I come back after applying a rule in Rewrite mode)
- [ ] when I switch from the Rewrite mode to the Search mode, I should open on my last search (now the text does not change) (see #318 about having a History in Search mode)
- [ ] when I switch from the Search mode to the Rewrite mode, most of the time it is because I want to apply a rewriting rule on the result of my search, so the Rewrite mode should open on a new rewriting rule where the first part is my previous search. (Note that the number of the rule must be the next number in my History, see #318)

**Comment by khansadaoudi** [comment]
@sylvainkahane I couldn't reproduce the issue of the 4 times click to switch to the other mode so I suggest you to click on the arrows like the screenshot to switch directly to the other mode 
![image](https://github.com/Arborator/arborator-frontend/assets/50585493/b6706de1-3277-4dad-9737-0a595e544c6c)
for the other suggestions, I will try to implement then asap, I will keep you updated when it's done
