### ISSUE TITLE
[Feature request]: Last trees as custom training parameter

### ISSUE THREAD

**Issue by RZiane** [Arborator/arborator-frontend#290]
### Is there already a feature request for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

As the platform is collaborative, we can have training data generated by several users. 

### Suggest a solution

It would be ideal to be able to select the last tree of each sentence in the training parameters. 
May be in the "Custom Training user" drop-down menu or another checkbox

Thanks in advance

**Comment by khansadaoudi** [comment]
Hey @RZiane, If you don't specify the custom user the paser will take by default the last trees of each sentence.
