### ISSUE TITLE
[Bug]: tokens : adding or splitting

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#295]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

when selecting a token or a sentence in the REF line (above the tree), nothing happens

### Steps To Reproduce

1. click on a sentence
2. the message "sélectionnez la phrase pour diviser les tokens" appears
3. select a token or the whole sentence
4. nothing happens

### What browsers are you seeing the problem on?

Firefox

**Comment by khansadaoudi** [comment]
@B-CARON You have to select only the token without including the white sapces between tokens
