### ISSUE TITLE
[Bug]: scary icon

### ISSUE THREAD

**Issue by kimgerdes** [Arborator/arborator-frontend#297]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

when logging in with Github, a space invaders icon is used instead of our AG icon:
![image](https://github.com/Arborator/arborator-frontend/assets/12749873/157b26bf-f293-4341-ac79-f83ad6ebf85f)

### Steps To Reproduce

just log out of Git Hub and log back in.

**Comment by khansadaoudi** [comment]
I have just updated it with AG logo in the github settings
