### ISSUE TITLE
[Bug]: you close you lose!

### ISSUE THREAD

**Issue by kimgerdes** [Arborator/arborator-frontend#299]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

when closing a modified tree (clicking on one's name on top) and reopening the tree (clicking again, the recent annotations are gone)!

### Steps To Reproduce

1. I add a subj link:
![image](https://github.com/Arborator/arborator-frontend/assets/12749873/dfbcd5b9-bdd4-4f6a-8729-5af4d72d3091)
2. I close the tree: 
![image](https://github.com/Arborator/arborator-frontend/assets/12749873/13c2518e-c852-4620-adaa-eb6b07b0247e)

3. I reopen the tree, and my new relation is gone! 
![image](https://github.com/Arborator/arborator-frontend/assets/12749873/823e97e9-36d2-45c8-858f-8aebab8dc2ff)

**Comment by bguil** [comment]
The same thing happens if you switch to another user while annoting.

**Comment by bguil** [comment]
I still have the problem when switching to another user.

**Comment by kirianguiller** [comment]
The commit was still not pushed to prod, but it fixed the problem correctly (normally). @khansadaoudi can evaluate if the bug is still here in production after the next deployement to prod !

**Comment by khansadaoudi** [comment]
@kirianguiller I still have the problem in the prod

**Comment by khansadaoudi** [comment]
the problem solved thank you @kirianguiller
