### ISSUE TITLE
[Bug]: internal server error 

### ISSUE THREAD

**Issue by CaroleWerner** [Arborator/arborator-frontend#315]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I encounter the following error 'internal server error' when I try to upload files in conll format. 

### Steps To Reproduce

import conll file 
click on upload
"internal server error" 

### What browsers are you seeing the problem on?

Firefox

**Comment by bguil** [comment]
Hi @CaroleWerner,

I've just tried to upload some conllu file on my project and i did not have the error oyu mentionned.

Can you tell us the name or your projet and send your Conll file such that we can check where the problem comes from.

**Comment by bguil** [comment]
J'ai créé un projet pour tester avec ce CoNLL: https://arboratorgrew.elizia.net/?#/projects/github_issue_315

Quand je sélectionne le fichier `test.conllu` qui contient les données du dernier message, j'ai un avertissement (copie d'écran jointe) car par convention dans UD ou SUD, chaque phrase doit avoir une métadonnée `sent_id` (i.e. une ligne `# sent_id = …` dans ce qui précèdent la phrase elle-même. 
<img width="830" alt="Screenshot 2023-12-22 at 09 00 59" src="https://github.com/Arborator/arborator-frontend/assets/687155/38420c59-38e5-4a67-8511-f00c98824fca">

Cependant, ArboratorGrew vous prosose d'ajouter des `sent-id` par défaut (en cliquant sur `CONTINUE`). Ensuite, il y a petit problème d'interface car le bouton "upload" n'est pas actif, mais en entrant un `userId` dans le champ au-dessous, on peut ensuite "uploader".

On a bien alors les trois phrases d'exemple dans l'échantillon `test`:  `https://arboratorgrew.elizia.net/?#/projects/github_issue_315/test`.

NB: ArboratorGrew a ajouté les `sent_id`: `test__1`… `test__3`.ca

@khansadaoudi @gguibon @kimgerdes @kirianguiller: je ne trouve aucune trace de ces données dans les logs. Le problème a du se produire dans le Flask.

@CaroleWerner: pouvez-vous essayer une nouvelle fois et nous dire l'heure où vous voyez l'erreur pour qu'on puisse comprendre?

**Comment by CaroleWerner** [comment]
Bonjour @bguil , 

Merci pour vos retours. Dans le projet Divital j'ai réussi à uploader 44 échantillons sans avoir défini de sent_id au préalable. ArboratorGrew m'avait affiché le même message d'erreur, mais cela n'avait ensuite pas posé de problème pour uploader mes échantillons. 
Dans mon nouveau projet Divital_YD (ni dans Divital d'ailleurs) il m'est devenu impossible d'uploader quoi que ce soit. J'ai testé d'uploader le fichier joint en ajoutant un send_id, mais le même message "... has sentences without send_id" continue de s'afficher. Quand je clique sur "continue" puis sur upload, le message d'erreur "internal server error" s'affiche encore : ![image](https://github.com/Arborator/arborator-frontend/assets/150339385/22b5922f-d353-4adb-9bf4-7bf44309251b)

[001_UD_ARBORATOR.txt](https://github.com/Arborator/arborator-frontend/files/13749970/001_UD_ARBORATOR.txt)

**Comment by bguil** [comment]
Il y a deux problèmes avec le fichier joint:
1. la ligne 4 (`# user_id = carolewerner`) car `user_id` est une métadonnée que ArboratorGrew utilise en interne et qui ne doit pas apparaître dans les données importées.
2. Il ne faut pas de ligne vide entre les métadonnées et la description des tokens. En conll, chaque ligne vide déclare une nouvelle phrase.

Donc en supprimant les lignes 4 et 6 du fichier (i.e. les données ci-dessous), il n'y a plus d'erreur d'import.

```
# sentence = Dü kâsch ílàde, wane àss de wett.
# source = Rünneburger p202
# UD NEW
# send_id = ex_001
1	Dü	_	PRON	_	Case=Nom|Number=Sing|Person=2|PronType=Prs|Polite=Infm	3	nsubj	_	_
2	kâsch	_	AUX	_	Mood=Ind|Tense=Pres|Number=Sing|Person=2|VerbForm=Fin	3	aux	_	_
3	ílàde	_	VERB	VerbForm=Inf	_	0	root	_	_
4	,	_	PUNCT	_	_	8	punct	_	_
5	wane	_	PRON	_	Case=Acc|Number=Sing|Person=3|PronType=Int	8	obj	_	_
6	àss	_	SCONJ	_	_	8	mark	_	_
7	de	_	PRON	_	Case=Nom|Number=Sing|Person=2|PronType=Prs|Polite=Infm	8	nsubj	_	_
8	wett	_	VERB	_	Mood=Ind|Tense=Pres|Number=Sing|Person=2|VerbForm=Fin	3	acl:relcl	_	_
9	.	_	PUNCT	_	_	3	punct	_	_


```

Autres remarques:
 - dans votre fichier, vous utiliser `send_id` au lieu de `sent_id` (`sent` pour "sentence")
 - la ligne 3 (`# UD NEW`) est ignoré car elle n'est pas de la forme `# NOM_DE_LA_METADONNEE = VALEUR_DE_LA_METADONNEE

**Comment by CaroleWerner** [comment]
merci pour votre aide!

**Comment by khansadaoudi** [comment]
I added different error messages based on the errors of your file
