### ISSUE TITLE
[Bug]:   Lexicon replacement icon missing

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#316]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the lexicon tool, after selecting the items to be modified, no icon is visible to switch to the replacement popup. It appeared when I clicked at random on the line of one of the items selected. 
![image](https://github.com/Arborator/arborator-frontend/assets/100767065/70f7f2e6-6757-4066-a94b-19fef5f6c835)
![image](https://github.com/Arborator/arborator-frontend/assets/100767065/d497011f-a3ea-4f07-aeb7-9f7e38f3e9ac)

### Steps To Reproduce

XX

### Project name

https://arboratorgrew.elizia.net/#/projects/HAU_ADER

### Anything else?

XX

### What browsers are you seeing the problem on?

Firefox

**Comment by khansadaoudi** [comment]
@B-CARON actually it's not bug, in order to modify item in the lexicon you have to click on the line of the concerned item and then you get the replacement dialog because you can only modify one item at a time. So maybe I will remove the selection option.
