### ISSUE TITLE
[Bug]: internal server error with rewriting rule

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#317]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the lexicon tool, I get an "internal server error" when testing a rewriting rule.
![image](https://github.com/Arborator/arborator-frontend/assets/100767065/3ed9b69f-3b84-4759-9fa6-628011435026)

![image](https://github.com/Arborator/arborator-frontend/assets/100767065/0fa251f8-14e0-4cce-9059-d443a7e930e6)

![image](https://github.com/Arborator/arborator-frontend/assets/100767065/78b6d7d6-6bf2-4ba8-917f-1c4a23c1b7f8)

### Steps To Reproduce

xx

### Project name

https://arboratorgrew.elizia.net/#/projects/HAU_ADER

### Anything else?

xx

### What browsers are you seeing the problem on?

Firefox

**Comment by khansadaoudi** [comment]
@B-CARON great, I tried to reproduce it in your project and it was working for me

**Comment by khansadaoudi** [comment]
I close it since it's working fine
