### ISSUE TITLE
Ordre des phrases

### ISSUE THREAD

**Issue by maigida** [Arborator/arborator-frontend#32]
Le même problème s'est reproduit de phrases ordonnées dans l'ordre décroissant.
Je ne vois pas ce qui peut causer ça: si j'efface le fichier et que je télécharge la copie CONLL de sauvegarde, c'est l'ordre croissant (normal) qui apparaît...
Ex. de fichier vérolé : https://arboratorgrew.ilpga.fr/#/projects/NAIJA-PRAAT_19.06/WAZP_04_Ponzi-Scheme_MG 
B.

**Comment by kirianguiller** [comment]
On vient d'avoir ce problème sur le projet : https://arboratorgrew.ilpga.fr/#/projects/SUD%20Chinese

Le conllu a été uploadé il y a deux semaines, et il est passé dans l'ordre décroissant dans l'après-midi.

**Comment by kirianguiller** [comment]
Si l'on regarde tout en bas du fichier (qui a été inversé), on peut voir les arbres qui sont normalement positionnés tout en haut MAIS ils sont séparés (voir photos ci-dessous). Par exemple, si 3 annotateurs avaient annoté le premier arbre, alors après l'apparition de ce bug, cet arbre se retrouve tout en bas en trois exemplaires.

**Comment by maigida** [comment]
Emmett a ce problème également en ce moment avec son corpus de dialogues naija

**Comment by bguil** [comment]
j’ai corrigé le code et les données côté Grew.

Normalement, il ne devrait plus y avoir de problème d’ordre des phrases dans les samples.
Si vous constatez encore des problèmes, merci de me signaler avec le nom du sample concerné.
