### ISSUE TITLE
Splitting sentences 

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#324]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to split sentences. It went OK until the last step where it refused to save the result. Is this new feature operational? 

### Steps To Reproduce

Clicks on Sentence segmentation
Followed the instructions 
Got the message "Error while splitting the sentence" when saving the result. 

### Project name

HAU_Ader

### Anything else?

![image](https://github.com/Arborator/arborator-frontend/assets/100767065/363462c0-f4eb-47e3-bc32-b0b2a17a4694)

### What browsers are you seeing the problem on?

Firefox

**Comment by bguil** [comment]
The backend server needed a restart! It should work now.
