### ISSUE TITLE
In the "Rewrite" section. Freezin the "copy" button 

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#325]
### Is there already a feature request for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

IN the rewrite section, when you have selected a rule from the history, the copy button remains at the top of the list. You need to scroll to the top of the list to click it. 

### Suggest a solution

Could you freeze the copy button to make it accessible anywhere in the list?

**Comment by khansadaoudi** [comment]
I have changed the interface of grew history so this issue is not existing anymore
