### ISSUE TITLE
Parser Bug

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#326]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

The parser gets stuck in the 1st phase: initialization 

### Steps To Reproduce

After selecting the files for training and/or parsing the parser goes into a loop at the 1st stage: 
![image](https://github.com/Arborator/arborator-frontend/assets/100767065/7098a231-2668-4412-b9e1-b818a49ae2e7)

### Project name

HAU_Zaria & HAU_Ader

### Anything else?

xxx

### What browsers are you seeing the problem on?

Firefox

**Comment by kimgerdes** [comment]
I confirm this bug. i've checked on the GPU backend, and there does not seem to be a process started when I start the training in the AG interface.
After restarting the GPU backend, it seems to work again, but the frontend should inform the user if it cannot reach the GPU backend.

**Comment by khansadaoudi** [comment]
Close this issue since we have added some error messages in the frontend to infrom user when there is a problem in the GPU backend
