### ISSUE TITLE
[Bug]: recency order of projects seems off

### ISSUE THREAD

**Issue by kimgerdes** [Arborator/arborator-frontend#327]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/Arborator/arborator-frontend/assets/12749873/ec41fcd4-a135-49e7-98a1-af8af39078c1)
how can someone modify without accessing it?

### Steps To Reproduce

Check the project page.

**Comment by khansadaoudi** [comment]
This problem has been resolved in the backend
