### ISSUE TITLE
[Feature request]: parser status information could be improved

### ISSUE THREAD

**Issue by kimgerdes** [Arborator/arborator-frontend#331]
### Is there already a feature request for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

when the parser runs, the information is shown in this way
![image](https://github.com/Arborator/arborator-frontend/assets/12749873/e17d69d1-a95e-49f9-ac7d-4a57b88bdad8)
this could be improved to some kind of table, possibly with some icons, and the LAS always rounded to 3 digits.
also, 
- once the parsing it's done, the user comes back to the original page which is not showing that the parsing has been completed.
- it would be good to prevent the user from leaving the page while the parsing happens (as i supposed, it will not finish the parsing, right?)
- the selection of the exisiting pre-trained models gets hard as there are so many now. it could be ordered/grouped by language/project and the pretrained_sud_all should be the default.

**Comment by khansadaoudi** [comment]
The parser interface has been impoved in the last commits, so I can close this issue
