### ISSUE TITLE
[Bug]: uploading big conll files

### ISSUE THREAD

**Issue by kimgerdes** [Arborator/arborator-frontend#332]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I wanted to train a parser on Naija SUD, so I combined the conllu files into one and uploaded it.
It just keeps spinning, but nothing happens.
![image](https://github.com/Arborator/arborator-frontend/assets/12749873/80ca0224-9d65-4db7-a32d-7b12dab34d34)

### Steps To Reproduce

make a big conllu file and upload it

### Anything else?

Could there be an indication of what I can upload maximally and a time-out to stop at one point?

Alternatively, the problem also could be fixed more basically by giving access to existing treebanks for training.

**Comment by kimgerdes** [comment]
I've just tried to load the separate Naija files, and there is a 413 error that is not caught:
![image](https://github.com/Arborator/arborator-frontend/assets/12749873/d0306d38-8de3-4112-9296-85484d584f8e)

**Comment by khansadaoudi** [comment]
This issue has been resolved you can make request with big data size
