### ISSUE TITLE
meta lines in CONLL

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#335]
### Is there already a feature request for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

In the new version of the CONLL interface, the meta lines are no longer visible. I absolutely need them, as they provide crucial information for the annotation. I my case, this is the phonetic line!

### Suggest a solution

restore the meta lines above the table.

**Comment by khansadaoudi** [comment]
Hello, the metalines are still available you can access and modify them from metadata dialog from here.
![image](https://github.com/Arborator/arborator-frontend/assets/50585493/f242c837-a2d0-4633-a3f2-50e160584157)
@B-CARON Do you want them to be merged in the same dialog ?

**Comment by khansadaoudi** [comment]
Close this issue since we added conll text view and the modification can be done in the metadata dialog
