### ISSUE TITLE
all-save when exiting a sample

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#336]
### Is there already a feature request for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

When exiting a sample, we sometime get the message that some modifications have not been saved. If I open the samples again, the orange icon showing that the sample has been edited without saving is no longer visible. 

### Suggest a solution

1° Include an option in the message allowing to save all modifications before exiting
2° An option to select in the general settings, for automatic saving when exiting Arborator
3° The orange icon remains even if the sentence is not developed on the screen

**Comment by bguil** [comment]
After a modification, if I use "validate", the annotation should be considered as saved. 
With the current version, after validation, I still have the red number "1" indicating an unsaved sentence.

**Comment by khansadaoudi** [comment]
Thank you @bguil  for testing, I fixed it.
