### ISSUE TITLE
Error while splitting sentence

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#338]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a recurring problem while splitting a sentence.
The original sentence gets duplicated at the end of the file. 

![image](https://github.com/Arborator/arborator-frontend/assets/100767065/8a0aec9c-a111-48a9-a832-3df72d559b8c)

![image](https://github.com/Arborator/arborator-frontend/assets/100767065/7356e984-6411-49bf-842b-af6741ec40be)

### Steps To Reproduce

XX

### Project name

HAU_Zaria

### What browsers are you seeing the problem on?

Firefox

**Comment by khansadaoudi** [comment]
Can't reproduce this issue can you confirm if it's always persistent
