### ISSUE TITLE
[Bug]: Bad order of users after sentence segementation

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#341]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I segmented a sentence. After the segmentation the users for the two parts of the sentence are in false (and different!!) order.
Order before segmentation: skahane > mohtahir1962 > DiegoRossini
Order of split1: DiegoRossini  > mohtahir1962 > skahane 
Order of split2: DiegoRossini  > skahane > mohtahir1962
So strange!
<img width="849" alt="image" src="https://github.com/Arborator/arborator-frontend/assets/23051796/4a153282-17f8-4ec2-b53f-7ba61f2aa5b7">

### Steps To Reproduce

Segment a sentence with several users.

### Project name

https://arboratorgrew.elizia.net/#/projects/bedja/BEJ_MV_NARR_15_LEOPARD

### What browsers are you seeing the problem on?

Firefox

**Comment by sylvainkahane** [comment]
Same problem after a fusion!

**Comment by sylvainkahane** [comment]
- [ ] Another small problem: I split a sentence with a very long translation. Only the beginning of text_en was visible and it was not possible to see the rest and to modify it. A cursor should be added.

**Comment by khansadaoudi** [comment]
The problem has been resolved the order of trees is saved now, for the second point you have to click on the input you will get the cursor you can use the right and left keys of the keyboard to scroll horizontally to the end of the input
