### ISSUE TITLE
[Feature request]: Feature names in lexicon

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#349]
### Is there already a feature request for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

In the lists proposed in the lexicon, form, lemma, and upos should be written without an uppercase.
<img width="513" alt="image" src="https://github.com/Arborator/arborator-frontend/assets/23051796/bfe36cae-82da-4aa9-b292-8965b5f8e974">

**Comment by khansadaoudi** [comment]
@sylvainkahane is it a convention to write them in lowercase

**Comment by sylvainkahane** [comment]
Yes it is the convention used by Grew : upos, lemma, form are names of columns in the conllu; Number, Gender … are names of features.
