### ISSUE TITLE
[Bug]: "reset to UD" not working

### ISSUE THREAD

**Issue by megasser** [Arborator/arborator-frontend#351]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I started my project with UD. Now it’s switched to SUD without my changing it, so I don’t have the appropriate relation options when creating an arc. I keep trying “reset to UD” and “Save annotation settings”, but I still only see the SUD options when creating an arc.

### Steps To Reproduce

1. Select uploaded treebank file.
2. Select sentence.
3. Select head word and pull bow to dependent.
4. Select from relation options (SUD options appear).
5. Go to treebank settings.
6. Select “reset to UD”.
7. Select “Save annotation settings”. (See “New annotation settings saved on server.”)
8. Repeat 1-4. SUD options still appear (for example, no “case”, no “nsubj”).

### Project name

EETB Project: Amharic

### What browsers are you seeing the problem on?

Firefox

**Comment by RZiane** [comment]
Hi Khensa, 

I created a new collection with the UD scheme as parameter. 
The UD scheme is well added to the "Annotation settings" but it's not operating. I had to save manually to make it work.

**Comment by khansadaoudi** [comment]
Hi Rayan,
Thank you for reporting this issue, I will fix it later.
