### ISSUE TITLE
[Bug]: applying grew rule on the "validated" trees does not updated the "validated" trees

### ISSUE THREAD

**Issue by sylvainloiseau** [Arborator/arborator-frontend#352]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running a grew rule, one can select the "validated" trees as target. In that case however, the result of the transformation does not appear under the "validated" trees, that stay untouched, but as belonging to the user running the rule.  If, in particular, only "validated" trees existed previously, new trees belonging to the user now appear.

### Steps To Reproduce

- open a Project with "validated" trees
- open the "Grew" panel through the bottom right button
- paste a query such as the following (assuming some trees are not annotated yet for the root dependancy)
`
rule r {
 pattern { X[]; ANCHOR[] }
 without { A0 []; A0 < ANCHOR }
 without { X < ANCHOR }
 without { Y []; X < Y }
 without { ANCHOR -[root]-> X }
 commands { add_edge ANCHOR -[root]-> X }
}
`
- select the "validated" as the subcorpus to apply the query upon
- run the query

**Comment by khansadaoudi** [comment]
Actually this happened when you're not validator or administrator because simple annotators can't apply rules on validated trees but they can visualize the rule on validated trees and then saved it under their username.
