### ISSUE TITLE
[Bug]: Most recent trees which are not most recent tress

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#358]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I search pattern { N [form="/", !TokenType] } on "Most recent trees", I obtain 4 matches.
But these 4 trees are not most recent trees.
When I apply the rule 
rule r { pattern { N [form="/", !TokenType] } commands { N.TokenType=Break } }
everything seems to go well, but in fact the rule didn't apply.

### Steps To Reproduce

It is possible that these trees have been produced by the split of a sentence.

### Project name

https://arboratorgrew.elizia.net/#/projects/bedja/BEJ_MV_NARR_15_LEOPARD

**Comment by bguil** [comment]
The problem should be fixed in data of the project "bedja".
