### ISSUE TITLE
[Bug]: correct rule but Internal Server Error

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#359]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

the following rule cannot be applied (Internal Servor Error)
rule r {
 	pattern { N [form="//", !TokenType] } 
 	commands { N.TokenType=Break
  }
}

### Steps To Reproduce

The request
pattern { N [form="//", !TokenType] } 
has 72 matches
but no rule can be applied on them.

### Project name

https://arboratorgrew.elizia.net/#/projects/bedja

### Anything else?

I suppose that one of the matches is problematic.

**Comment by khansadaoudi** [comment]
This issue concerned only the data of Bedja project. I tried the rule and it works fine now after Bruno's updates so I will close this issue
