### ISSUE TITLE
slow project hub

### ISSUE THREAD

**Issue by gguibon** [Arborator/arborator-frontend#36]
Very slow project hub when too many projects are registered

**Comment by kimgerdes** [comment]
this still seems quite slow, even in the new version. it would be nice to be able to archive projects into some kind of of archive folder if they haven't been used for some time (and take them out by using them)

**Comment by kirianguiller** [comment]
up, this is important to fix

**Comment by bguil** [comment]
More information needed. 
I've observed: Clinking on Access Treebanks take 4s to respond.
Maybe wait for #85 with info on requests times?

**Comment by sylvainkahane** [comment]
Ce point est carrément bloquant pour l'utilisation de arboratorgrew dans des pays comme le Nigeria où les connexions sont mauvaises. Bernard en a fait l'amer expérience dernièrement.
L'accès a ag ne devrait pas nécessiter de charger la liste complète des treebanks sur la machine de l'utilisateur, mais seulement les 10 plus récents ou utilisés récemment. D'autant qu'en général on va directement dans le ligne de recherche pour taper le nom d'un treebank.

**Comment by gguibon** [comment]
- [x]  20 % speed up from [this commit](https://github.com/Arborator/arborator-backend/commit/5bc74e0bc6837c5398b3baecc295c16a443d025d)
- [ ] by step loading process

**Comment by gguibon** [comment]
Done and pushed to prod. I create another "improvement" issue in regards to lazy loading controllers.
