### ISSUE TITLE
[Feature request]: mark as "validated" all the trees of a sample

### ISSUE THREAD

**Issue by sylvainloiseau** [Arborator/arborator-frontend#368]
### Is there already a feature request for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

Some functions rely on the trees being marked as "validated". For instance, the synchronisation process between arborator and GitHub can commit only the trees marked as "validated". It is tedious to skim all conll (sample), open all trees, and mark them as validated, in order to have the tree committed.

### Suggest a solution

It would be great to have a button offering to mark as "validated" all the (last version of) trees of a sample.

**Comment by khansadaoudi** [comment]
We added new mode non collaborative mode when user works only on the validated trees, so they don't have to validate all trees in order to commit them to github
