### ISSUE TITLE
Saving but not validating when using a rewriting rule

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#369]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

When saving the results of a rewriting rule, the trees are saved but not validated! If you want to synchronise your work with the GIT, you have to open each sample, filter it to show the changed trees, and validate each one manually. I've just done it for 121 trees!!! It's repetitive, stupid and boring. I suggest the owner/manager of a project should have his changes validated by default, not just saved. 
 

### Steps To Reproduce

xxx

### What browsers are you seeing the problem on?

Firefox

**Comment by sylvainkahane** [comment]
Validation (or github status) must be just a tag attached to the tree of one user. When you change this tree and save it, if its already a tree on your name, the tags must remain on the tree of course. When you change the tree of another user, I don't know what must happen. I depends on the respective status of the users and the parametrizing of the project. But I don't want another user to be authorized to change a tree I validated without knowing it. Something is fucked up from the beginning.

**Comment by khansadaoudi** [comment]
There is the possibility to apply the rule directly on the validated trees, in this case you don't have to validate each tree manually.
