### ISSUE TITLE
[Bug]: Changing the head of the token from the conllu table

### ISSUE THREAD

**Issue by Nataroma** [Arborator/arborator-frontend#370]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we try to manually change the head of a token from the conllu table, we get an error message.

### Steps To Reproduce

1. From a tree's menu go to "Obtenir le CONLL-U de cet arbre"
2. In the HEAD column, change the value, e.g. "5" to "3"
3. There is a message in purple "HEAD value must be either -1 or 0 or < sentence length"
4. It is impossible to save the change

### Project name

MICLE_1553_Guernsey, Gascon_1460_Les_Fors_anciens_de_Bearn 

### Anything else?

![image](https://github.com/Arborator/arborator-frontend/assets/33596273/df6ba838-9102-4f56-951a-031e8a69132f)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

**Comment by bguil** [comment]
I confirm the bug. We try to fix this soon.

**Comment by khansadaoudi** [comment]
This issue has been resolved in the last commit

**Comment by Nataroma** [comment]
THANK YOU!!!
