### ISSUE TITLE
Enhanced dependencies annotation on trees 

### ISSUE THREAD

**Issue by adripag** [Arborator/arborator-frontend#374]
I have tried editing enhanced relations in the Table view but whenever I save modifications I get an error.

<img width="1386" alt="Screenshot 2024-05-06 at 11 48 09" src="https://github.com/Arborator/arborator-frontend/assets/80424602/ce519b18-26b6-48a1-9c94-403463debd2b">

Also, is there any plan to develop Arborator grew so that it can allow annotating enhanced dependencies by dragging and clicking the tree visualization?

Many thanks and congrats on your excellent work!

**Comment by khansadaoudi** [comment]
Thank you @adripag, your issue has been resolved. 
For the moment we are not planning to implement the graphic annotation for enhanced dependencies in the short term but you still can use the table view for that annotation.
