### ISSUE TITLE
[Bug]: "save" button does not work for changes in column 9 of the CoNLL-U (table mode).

### ISSUE THREAD

**Issue by MagaliDuran** [Arborator/arborator-frontend#375]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to edit enhanced dependencies in the table mode, but when I press the button to save, a message appears: "Unknown error, please contact the administrators". 

### Steps To Reproduce

1- I open a sentence
2- I choose "get CoNLL-U of this tree"
3- I choose "table view"
4- I edit some column 9 content 
5- I press "ok"
6- a warning appears to save the tree
7- I press the "save" button
8- an error message appears "Unknown error, please contact the administrators"

### Anything else?

![IMG-20240506-WA0012](https://github.com/Arborator/arborator-frontend/assets/77698300/6aa17fb5-b395-47dd-abe2-558cd76cbbd5)

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by bguil** [comment]
@MagaliDuran: It works for me. If you use the syntax like `3:subj|4:obj` the graph can be saved.

Maybe you should do a "force refresh" to be sure to have the last fixed of #374.

**Comment by MagaliDuran** [comment]
Hi, Bruno!

Finally it worked for me too!
Thank you so much for your help.

Magali

Em ter., 7 de mai. de 2024 às 16:27, Bruno Guillaume <
***@***.***> escreveu:
