### ISSUE TITLE
[Feature request]: split a sentence after the first tree

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#376]
### Is there already a feature request for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

Most of the time, we do the sentence segmentation when we already have an annotation of the beginning. 

### Suggest a solution

So it would be nice to have a special option which is "Split after the first tree".

**Comment by khansadaoudi** [comment]
I will close this issue since it's mentionned here [#399](https://github.com/Arborator/arborator-frontend/issues/399)
