### ISSUE TITLE
[Bug]: No Connection to API

### ISSUE THREAD

**Issue by DanielCasas21** [Arborator/arborator-frontend#377]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to parse some sentences and I keep getting this error message: 

Parsing could not start : <ArboratorParserAPI> connection timout with `url=http://calcul-kimgerdes.lisn.upsaclay.fr:8002/parser/models/parse/start`

### Steps To Reproduce

I choose a model to parse new sentences, 
I select the sentences I want to parse, 
I start parsing

### What browsers are you seeing the problem on?

Firefox

**Comment by kirianguiller** [comment]
Hello,

It's fixed. Thank you for the issue. 
The problem originate from the fact that server hosting the parser was corrupted last week and we had to reinstall everything from scratch.
However, during the reinstallation, we forgot to install Redis, which is a dependency of our parser server (used to manage tasks queuing).

It's now fixed and better documented in the parser [server documentation](https://github.com/Arborator/arborator-parser).

Thank you again and sorry for the bug.
