### ISSUE TITLE
[Feature request]: Is there a feature setting for right-to-left languages in project setup?

### ISSUE THREAD

**Issue by farukmardan1030** [Arborator/arborator-frontend#380]
### Is there already a feature request for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

I'm trying to create a project for Uyghur which is written right to left. However, I cannot find the setting in the project setup to configure this feature.

**Comment by khansadaoudi** [comment]
@farukmardan1030 We have solved the problem now you can choose RTL option when you upload your sample by checking on the RTL checkbox in the upload dialog

**Comment by fadhleryani** [comment]
The text is RTL when selecting this option, but the trees are LTR.
