### ISSUE TITLE
[Bug]: Uploading file

### ISSUE THREAD

**Issue by RZiane** [Arborator/arborator-frontend#382]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi Khensa, 
Although it is stated in the pop-up for uploading a file that the default userID will be that of the user, it is currently necessary to specify it.

### Steps To Reproduce

1. Open uploading menu
2. Try to upload after selecting a file

**Comment by khansadaoudi** [comment]
@RZiane I can't reproduce your problem because the username input is prefilled by your current username isn't it.

**Comment by RZiane** [comment]
I think I've found the problem. When we open the project page for the first time, if it's the first upload, our username is filled in correctly by default. However, if we delete the name, after refreshing the page, the username is no longer displayed by default.

**Comment by khansadaoudi** [comment]
@RZiane, I have made some changes in the UI in order to avoid typing error in case you want to upload your trees under your username or as validated trees.
