### ISSUE TITLE
[Bug]: Flipped Word Order

### ISSUE THREAD

**Issue by DanielCasas21** [Arborator/arborator-frontend#383]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, 

I'm trying to add new samples by uploading them as text, but once the parser tokenises them, it displays them flippled, with the first word appearing as the last one. I've tried toggling RTL configuration on and off, with the same result. The Conllu file seems to be in the correct order, it's just weird this layout and the syntactic tree looks odd.

### Steps To Reproduce

1. Add new samples
2. Input text
3. Select tokenize option: horizontal
4. (Optional) Toggle RTL configuration 

### Project name

Palenquero_v2

### Anything else?

<img width="312" alt="Screenshot 2024-07-20 at 14 45 57" src="https://github.com/user-attachments/assets/3a610f2d-ae18-4c77-887a-3c8c9dac5cda">
<img width="1006" alt="Screenshot 2024-07-20 at 14 48 50" src="https://github.com/user-attachments/assets/7c35e01f-4e45-4b1c-9087-a0568daefc85">
<img width="1006" alt="Screenshot 2024-07-20 at 14 48 57" src="https://github.com/user-attachments/assets/a2a9169d-1fc6-418a-9979-0e887684e943">
<img width="464" alt="Screenshot 2024-07-20 at 14 57 27" src="https://github.com/user-attachments/assets/259ec9b6-56cb-4359-a50a-4382e53cb5b1">
<img width="394" alt="Screenshot 2024-07-20 at 14 57 57" src="https://github.com/user-attachments/assets/06e6ac9f-0b9f-4420-81e7-195a8b8ef6ca">

**Comment by khansadaoudi** [comment]
@DanielCasas21 The problem has been resolved, I suggest you to reupload your data in new sample
