### ISSUE TITLE
[Bug]: Split token

### ISSUE THREAD

**Issue by shoowadoo** [Arborator/arborator-frontend#384]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am not having success using the split token feature. The pic upload is how I've entered the fields, and the result is the same as before. There is no change after hitting "SPLIT". For this sentence, the correct tokenization should be "did" and "n'" not "didn" and "'" .  

 I have also had the same issue splittling "I've" for instance. 

<img width="579" alt="Bildschirmfoto 2024-08-07 um 10 49 01" src="https://github.com/user-attachments/assets/c84b1fe4-51a2-4a87-9782-3882192c5fee">

<img width="878" alt="Bildschirmfoto 2024-08-07 um 10 49 27" src="https://github.com/user-attachments/assets/2c980dd2-ca6f-4ae3-a126-118b0808fffd">

### Steps To Reproduce

1. Highlight the word to edited. 
2. Select: Split token
3. Fill in the form and check 'Add multiword token'
4. Select 'SPLIT'
5. The menu to merge, split, insert, or delete pops up again 
6. Try steps 2-4 one more time. Form is still filled out as before, so I don't have to reenter anything. I just select 'SPLIT' again
7. This time, the menu does not pop up, but there is no change to the sentence. 

### Project name

HuckleberryFinnDialects_UD

### What browsers are you seeing the problem on?

Chrome

**Comment by khansadaoudi** [comment]
@shoowadoo from your screenshot, it looks like there is already two tokens "didn" and " ' ", you just need to change the form of the second token to be like " n' "

**Comment by shoowadoo** [comment]
Oh yes, I think you mean I could probably just do this manually. However, I have had the same issue with splitting other words which are not already split. (What you see here was the incorrect segmentation from UDPipe).

**Comment by shoowadoo** [comment]
Here's an example where the tokens were not already split. And using the splitting feature did not change the sementation. 

<img width="578" alt="Bildschirmfoto 2024-08-07 um 15 33 16" src="https://github.com/user-attachments/assets/aebfc620-8433-4ccd-b4fd-4d5023d79e4b">
<img width="592" alt="Bildschirmfoto 2024-08-07 um 15 33 48" src="https://github.com/user-attachments/assets/bb44d57f-4622-46cf-8476-0cde62fbbda5">

**Comment by khansadaoudi** [comment]
The feature is updated so i can close this issue
