### ISSUE TITLE
[Bug]: Sentence Segmentation: Merge 

### ISSUE THREAD

**Issue by shoowadoo** [Arborator/arborator-frontend#385]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

When merging two sentences into one, every token from the second sentence which is merged with the first gets tagged as root automatically. 

<img width="1404" alt="Bildschirmfoto 2024-08-07 um 11 29 09" src="https://github.com/user-attachments/assets/c922720f-9889-41fd-a56d-00ec063dd68e">

### Steps To Reproduce

1. Select sentence segmentation 
2. select segmentation option: merge
3. select the sent_id of the phrase you wish to merge with the current phrase
4. select "SHOW RESULT" 

### Project name

HuckleberryFinnDialects_UD

### What browsers are you seeing the problem on?

Chrome

**Comment by shoowadoo** [comment]
Was closed, but not resolved.

**Comment by shoowadoo** [comment]
Thank you. I did try it again, with the same problem results. Then I refreshed. I see that it works now. Thank you for tackling this so quickly. Well done!

**Comment by sylvainkahane** [comment]
The merge operation merges two sentences of the same annotator. If you merge S1 and S2 and you don't have a tree for S2, you obtain the "all root" tree.
@khansadaoudi I think that two things could be done:
1) inform the user that she has not the last tree for S2 and so propose two choices: choose the last tree for S2 or choose the tree of the user.
2) If S2 has no tree, just keep it without dependencies. Don't add the root dependencies.
