### ISSUE TITLE
[Bug]: Projects disappearing 

### ISSUE THREAD

**Issue by AngelicMcPherson** [Arborator/arborator-frontend#386]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am unable to open some of my projects, or create new ones. I also have other annotators on these projects, and they have the same issue. When attempting to open I get this message: Doh! There's nothing here...(404)

### Steps To Reproduce

1. Open the project
2. See error screen

### What browsers are you seeing the problem on?

Chrome

**Comment by khansadaoudi** [comment]
@AngelicMcPherson can you give the name of these projects

**Comment by khansadaoudi** [comment]
@RZiane I was fixing some issues in the prod server but it should work now

**Comment by AngelicMcPherson** [comment]
> @AngelicMcPherson can you give the name of these projects

The project is called POS Annotations. I attempted to create another new project called New POS Annotations and the same error occurred.

**Comment by RZiane** [comment]
@khansadaoudi Thanks

**Comment by khansadaoudi** [comment]
@AngelicMcPherson, your problem is that you added a white space at the end of the projects names when you created them or after you rename them. I suggest you to avoid using white space while naming your project, meanwhile I will add more validation rules for the project name input.

**Comment by AngelicMcPherson** [comment]
Will do moving forward! Is it possible to get access to my POS Annotations project despite the error?

**Comment by khansadaoudi** [comment]
@AngelicMcPherson we have solved your issue now you can access to your project.

**Comment by AngelicMcPherson** [comment]
Thank you! I have access to the project but unfortunately the file has disappeared. Is there a fix for this?

**Comment by AngelicMcPherson** [comment]
> @AngelicMcPherson we have solved your issue now you can access to your project.

Thank you! I have access to the project but unfortunately the file has disappeared. Is there a fix for this?

**Comment by bguil** [comment]
@AngelicMcPherson: I've found three files that were uploaded to ArboratorGrew. Can you contact me by mail at Bruno.Guillaume@inria.fr. I will send you these files directly and let you upload them to ArboratorGrew if needed.
