### ISSUE TITLE
[Bug]: Export trees from other users

### ISSUE THREAD

**Issue by RZiane** [Arborator/arborator-frontend#387]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi Khensa, 

I can't export trees from other users. When I select the option, I can't open the drop-down menu with the users currently on the project and choose the ones I want to export.

I tried on brave and firefox.

### Steps To Reproduce

1. Click on the export button
2. Select Export trees from other users
3. Click on the drop-down menu below

### Project name

Gascon_1460_Les_Fors_anciens_de_Bearn

**Comment by khansadaoudi** [comment]
Hey @RZiane the problem is solved now
