### ISSUE TITLE
Metadata édition

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#39]
Dans l'interface "Edit this tree's metadata", je pense que les metadonnées `sent_id` et `user_id` devrait être en read-only. Il n'y a pas de raison de changer ses données. D'ailleurs quand on essaie, on a  `Request failed with status code 400` au moment de la sauvegarde.

**Comment by kirianguiller** [comment]
Les récentes updates ont corrigées les points que tu mentionnes. Merci ! :)
