### ISSUE TITLE
[Bug]: Samples disappear

### ISSUE THREAD

**Issue by JMGarciaMiguel** [Arborator/arborator-frontend#390]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was using Grewmatch to revise a sample and now a get an error message: 

> "Grew internal error : GREW-ERROR : Conll_error: { "message": "Wrong number of fields: 2 instead of 10 expected", "file": "/home/guillaum/arborator_grew/storage/test_gl/USO", "sent_id": "2436", "line": 86396, "library": "Conll" }"

And now I cannot access neither that sample to correct the error nor any other of the samples of my project

### Steps To Reproduce

1. Open project test_gl (12 samples)
2. Error message:

> "Grew internal error : GREW-ERROR : Conll_error: { "message": "Wrong number of fields: 2 instead of 10 expected", "file": "/home/guillaum/arborator_grew/storage/test_gl/USO", "sent_id": "2436", "line": 86396, "library": "Conll" }"

4. Nothing in the list of samples

### Project name

test_gl

### What browsers are you seeing the problem on?

Firefox

**Comment by bguil** [comment]
@JMGarciaMiguel, the server crashed during the upload of one of your file.
The sample named `USO` is then truncated in the middle of a line, this explains the format error.

I've modified the data to make the format correct be removing the last lines.
You should be able to access to it, with only 2435 sentences in the samples `USO`.

**Comment by JMGarciaMiguel** [comment]
Ok. Thank you very much

El 30 ago 2024, a las 15:12, Bruno Guillaume ***@***.***> escribió:



@JMGarciaMiguel<https://urldefense.com/v3/__https://github.com/JMGarciaMiguel__;!!D9dNQwwGXtA!TIs4VTVIxs2UoRdBQxv_y0lxe2nMsFygF09f-RzY5nlobilk5sLZ70bjJborjNF-RDybqs3so0KAGQsOkntRsIKCog$>, the server crashed during the upload of one of your file.
The sample named USO is then truncated in the middle of a line, this explains the format error.

I've modified the data to make the format correct be removing the last lines.
You should be able to access to it, with only 2435 sentences in the samples USO.

**Comment by khansadaoudi** [comment]
I will close this issue since it concerns only a specific project.
