### ISSUE TITLE
[Bug]: annotation settings default reset

### ISSUE THREAD

**Issue by HugoDumoulin0** [Arborator/arborator-frontend#392]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

When starting a new projet I cannot set new annotation settings. After having saved them to the server, I can use them to annotate the samples. Unfortunately, they reset as soon as I refresh the page.

### Steps To Reproduce

1. start a new project 
2. set new annotation settings
3.  save them to the server
4. refresh the page
5. they reset to default settings

### Project name

M2 MEEF 1er degré

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

**Comment by bguil** [comment]
Thanks for reporting.
We have identified the problem. It should be fixed in the next few days.

**Comment by MagaliDuran** [comment]
I noticed a similar problem in my projects: the annotation settings were automatically reset to default settings.

**Comment by khansadaoudi** [comment]
The problem has been fixed.
