### ISSUE TITLE
[Bug]: Where is Grew in the new version of Arborator-Grew? 

### ISSUE THREAD

**Issue by MagaliDuran** [Arborator/arborator-frontend#393]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used to use Grew a lot to search my Arborator projects. However, I couldn't find the button to open the search tool in the new version of Arborator-Grew. 

### Steps To Reproduce

This is a general doubt.

### What browsers are you seeing the problem on?

Chrome

**Comment by khansadaoudi** [comment]
You find Grew in the project page when you switch the tabs you can find all features related to the samples in project 
![image](https://github.com/user-attachments/assets/ef7293cb-fa10-4470-921c-112439e53133)

**Comment by MagaliDuran** [comment]
Thank you a lot!
