### ISSUE TITLE
[Bug]: Difficult to split a token at the end of the sentence

### ISSUE THREAD

**Issue by Poslovitch** [Arborator/arborator-frontend#395]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to split the last token (`règle.`) of this sentence : 
> Sur ses maigres produits leur appétit se régle.

I find it difficult to manage to make the split/merge UI appear, as double clicking either selects **régle** or the whole sentence alternatively.

### Steps To Reproduce

1. Import a sentence ending with a *dot* (other punctuation not tested) that **is not spaced from the last word**.
2. Start annotating it on Arborator
3. Try to make the split UI appear by double-clicking on the last word of the sentence.

### Anything else?

I managed to make this work once, but I haven't been able to replicate this consistently, which is why I consider this a bug.

### What browsers are you seeing the problem on?

Firefox

**Comment by khansadaoudi** [comment]
Hi @Poslovitch, thank you for reporting this issue, can you post a full screenshot of your tree

**Comment by Poslovitch** [comment]
Here are screenshots for two occurrences (on in-progress trees):

![Sur_ses_maigres_produits_leur_appétit_se_régle Poslovitch](https://github.com/user-attachments/assets/5e11fce3-c2d2-40fb-9c1d-76b43db286d8)

![Le_ciel_a_révélé_ses_secrets_à_la_terre Poslovitch](https://github.com/user-attachments/assets/e8b8fcb6-2f8f-45c6-9048-09265a3b1277)

**Comment by khansadaoudi** [comment]
The issue is fixed currently if the problem is persitant don't hesistate to reopen it

**Comment by Poslovitch** [comment]
Can confirm it's fixed, although a bit tricky to use! I think a "redo" of how it's done should be in order - do you mind me submitting a proposal for this feature in the next week?

**Comment by khansadaoudi** [comment]
@Poslovitch, yes for sure. All contributions are welcome. 
And yes you're right this feature is very complicated to use, we are trying to change it and add it in the Conll table view
