### ISSUE TITLE
[Bug]: Parser keeps going on for ever

### ISSUE THREAD

**Issue by DanielCasas21** [Arborator/arborator-frontend#396]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi!

I've been trying to parse a new sample [perez_tejedor_anexo_2_1](https://arboratorgrew.elizia.net/#/projects/Palenquero_v2/perez_tejedor_anexo_2_1) using a previously trained model (Palenquero_v2_2024-09-23_13:06:56.059). However, it keeps going on for a long time without ever finalising the parsing.
<img width="1449" alt="Screenshot 2024-09-25 at 15 31 10" src="https://github.com/user-attachments/assets/e0986881-6624-451f-8e1a-ddf99103d918">

I received an email saying that it there was going to be an update to the user interface. Does this have to do with that?

Many thanks,

Daniel

### Steps To Reproduce

1.  Enter Palenquero_v2 treebank
2. Click on "parser" tab
3. Search Palenquero_v2 model
4. Choose Base model : Palenquero_v2_2024-09-23_13:06:56.059
5. Parse only one sample: perez_tejedor_anexo_2_1
6. Click on "Start"

### Project name

Palenquero_v2

### What browsers are you seeing the problem on?

Firefox

**Comment by stavros-bompolas** [comment]
Hi all,

I wanted to check if there have been any updates regarding this issue. I’ve been experiencing a similar problem. The parsing process takes an unusually long time and never seems to finalize.

Thanks in advance!

**Comment by DanielCasas21** [comment]
Hi all! 

I'm still experiencing this issue. I thought it was only me or that I had something wrong going on with my data. I even created a new account and tried all over again, but still the site had the same behaviour.

I hope this gets looked into soon.

Best,

Dan

**Comment by khansadaoudi** [comment]
Thnak you for reporting this issue we will try to fix it soon

**Comment by khansadaoudi** [comment]
The parser is available now can you test it and confirm if it's working for you too.

**Comment by stavros-bompolas** [comment]
Update: Issue Recurrence

Although the initial problem was resolved, the issue has reappeared. The following error message is now displayed:

<ArboratorParserAPI> unknown error when connecting `url=http://calcul-kimgerdes.lisn.upsaclay.fr:8002/parser/models/parse/status` : 'NoneType' object has no attribute 'get'

**Comment by khansadaoudi** [comment]
@stavros-bompolas The problem has been resolved can you test it and tell if it works fine for you now.

**Comment by stavros-bompolas** [comment]
@khansadaoudi I tested both the training and parsing functionalities, and everything works perfectly now. Thank you very much for your prompt attention and support!
