### ISSUE TITLE
Squished search results visualisation

### ISSUE THREAD

**Issue by marinecourtin** [Arborator/arborator-frontend#4]
When searching in a whole project
![Capture d’écran de 2020-05-05 14-27-07](https://user-images.githubusercontent.com/28790155/81066246-1afe2000-8edd-11ea-98a6-d1b32838076f.png)

When searching in a sample
![Capture d’écran de 2020-05-05 14-27-29](https://user-images.githubusercontent.com/28790155/81066252-1c2f4d00-8edd-11ea-90b8-7d5b294228f9.png)

**Comment by kimgerdes** [comment]
solved
