### ISSUE TITLE
[Bug]: invisible tokens

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#400]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a sentence with tokens that are not visible in the text. I would like to suppress them, but I cannot because I cannot select them.
<img width="1347" alt="image" src="https://github.com/user-attachments/assets/162a26b2-afbd-427e-9854-515d54044873">
Additional remark: the token "xxx" was an empty token. Using the table format, I add xxx in form and lemma, but the problem remained.

### Steps To Reproduce

I suppose that something in the conllu is bad (it is an export form Elan) and should have been refused.

### Project name

https://arboratorgrew.elizia.net/#/projects/Gbaya/CORRECT_GYA_PRD_NARR_01_T16-C6

### Anything else?

Can you suppress the invisible tokens? They shouldn't be there.

### What browsers are you seeing the problem on?

Firefox

**Comment by khansadaoudi** [comment]
I have just pushed on the prod new version of token modification you can click directly on the token and delete it from features dialog or from conll table view when you right click on the row of the concerned token.
![edit-tokens](https://github.com/user-attachments/assets/27b78b72-7e2f-43d3-a004-58d8863e3dc7)
![edit-tokens-2](https://github.com/user-attachments/assets/0977d6d7-9486-42f3-adb4-543a96589585)
