### ISSUE TITLE
[Bug]: extra quotes in text

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#401]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="977" alt="image" src="https://github.com/user-attachments/assets/b3399722-ae20-4c46-9362-e78c5e6e601d">

### Steps To Reproduce

The text is not the concatenation of token's forms.

### Project name

https://arboratorgrew.elizia.net/#/projects/Nenets/nar_RouDes_2017_04_26_001_yrk-tun

### What browsers are you seeing the problem on?

Firefox

**Comment by khansadaoudi** [comment]
This problem has been solved
