### ISSUE TITLE
[Bug]: No link between "text" and tokens in tree

### ISSUE THREAD

**Issue by RZiane** [Arborator/arborator-frontend#402]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi Khensa, 

There's a bug concerning the link between the text (tokens editor) and the tokens in the tree. 
Segmentation of tokens in the text has no effect on tokens in the tree:

![image](https://github.com/user-attachments/assets/d05bca7e-6f3b-43bf-a36e-cdeb7ac86a17)

### Steps To Reproduce

1. Split token in the text

### Project name

https://arboratorgrew.elizia.net/#/projects/Gascon_23

**Comment by khansadaoudi** [comment]
Hi Rayan,
I have just updated the split token feature. The token options are available in the feature dialog or you can get them from conll table view when you right click on the token row. So now the text displayed in the tree view is the same text of your text metadata in your conll.
