### ISSUE TITLE
[Bug]: Validation of replacement rule

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#404]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have created a project (SUD_Zaar-Autogramm) with 1 user, so that all changes are saved as Validated to make sure they are properly synchronised. If I use a replacement rule and save the results, they are saved under my user name, not as validated. 

### Steps To Reproduce

XXX

### Project name

SUD_Zaar-Autogramm

**Comment by khansadaoudi** [comment]
The issue has been resolved. You can remove the trees saved under your name
