### ISSUE TITLE
[Bug]: Can not update through Grew the trees of specific user

### ISSUE THREAD

**Issue by NeldaKote** [Arborator/arborator-frontend#406]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, 

I am the owner of the project and I tried run the following rule in Grew for  the tree of a specific user that is admin in my project.
rule r {
  pattern { e: Y -[mark]-> X; X [upos=PART, lemma="u"]; }
  commands { X.upos = AUX;  e.label = aux;}
}

Arborator notifies that the rule is applied.
![image](https://github.com/user-attachments/assets/38d5c4cd-8e83-4929-8a44-63951fd00bbc) 

But in reality the tree is not updated.

Thank you!

Nelda

  

### Steps To Reproduce

Update through Grew the trees of specific user

### Project name

SALT

### What browsers are you seeing the problem on?

Chrome

**Comment by khansadaoudi** [comment]
Actually in ArboratorGrew, users can't modify the trees of other users. So, if you apply rule on trees of specific user the changes will be saved under your name. Except for validated trees admins and validators can apply directly rules on these trees
