### ISSUE TITLE
[Bug]: Only 11 samples visible

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#409]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

The display opens on "records per page = 50" but only 11 of the 18 files are visible

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/57bd1733-afa2-46a1-88f2-671e07a27d90">

### Steps To Reproduce

When I change for 15 records or when I come back to "records per page = 50", I can see all the files.

### Project name

https://arboratorgrew.elizia.net/#/projects/bedja

### What browsers are you seeing the problem on?

Firefox

**Comment by khansadaoudi** [comment]
I can't reproduce this issue and from your screenshot it looks like it was just loading and because of that you didn't get all the samples. Reopen this issue if it's always persistent
