### ISSUE TITLE
Unable to upload conll file

### ISSUE THREAD

**Issue by abalvet** [Arborator/arborator-frontend#41]
I am unable to upload conll files in my projects, even files that are already present on the platform...
My files looks like this: 

# user_id = test
# sent_id = Corpus_illustratif_fr_1
# text = Je marche le long de la plage	
1	Je	cln	CL	CLS	s=suj	2	suj	_	_
2	marche	marcher	V	V	m=ind	_	_	_	_
3	le	le	D	DET	_	4	det	_	_
4	long	long	N	NC	s=c	2	mod	_	_
5	de	de	P	P	_	4	dep	_	_
6	la	le	D	DET	_	7	det	_	_
7	plage	plage	N	NC	s=c	5	obj.p	_	_
8	.	.	PONCT	PONCT	_	2	ponct	_	_

# user_id = test
# sent_id = Corpus_illustratif_fr_2
# text = Je marche la nuit dans une rue sombre.
1	Je	cln	CL	CLS	s=suj	2	suj	_	_
2	marche	marcher	V	V	m=ind	_	_	_	_
3	la	le	D	DET	_	4	det	_	_
4	nuit	nuit	N	NC	s=c	2	mod	_	_
5	dans	dans	P	P	_	_	_	_	_
6	une	un	D	DET	_	7	det	_	_
7	rue	rue	N	NC	s=c	2	mod	_	_
8	sombre	sombre	A	ADJ	_	7	mod	_	_
9	.	.	PONCT	PONCT	_	2	ponct	_	_

**Comment by kimgerdes** [comment]
Hello,
the error reporting of the new Arborator Grew is still incomplete. it is possible that the backend was down, or that the conll file had some bugs. maybe you can point us to the conll file so that we can try it out?
