### ISSUE TITLE
[Bug]: Erreur for connection

### ISSUE THREAD

**Issue by QishenWU** [Arborator/arborator-frontend#413]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is a probleme of connection this morning, I can't get access to any of my project.

### Steps To Reproduce

Just connect you'll see there is nothing on the site

**Comment by bguil** [comment]
We are aware of this problem. The server running ArboraborGrew is currently unavailable.

We have reported the problem upstream and I cannot say when it will be available. Sorry for the inconvenience.

**Comment by bguil** [comment]
ArboraborGrew is back! Thanks for your patience.
