### ISSUE TITLE
[Bug]: Documentation page for rewriting rules inaccessible

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#421]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

when clicking the 'documentation' in GREW re-writing rules, you get an error (blank page)
(https://grew.fr/doc/commands/) 

### Steps To Reproduce

XXX

### Project name

All my 3 projects (B-CARON)

**Comment by bguil** [comment]
This is fixed.
