### ISSUE TITLE
[Bug]: Error 500 X during validating

### ISSUE THREAD

**Issue by gracanunes** [Arborator/arborator-frontend#422]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

The same problem reported yesterday: the message of error 500 X appears every time I try to save something.

### Steps To Reproduce

Try to save anything in the pojects

### Project name

JUR_STF and JUR_STJ

**Comment by khansadaoudi** [comment]
Thank you for reporting, the issue is solved now. If you still have, you don't have to create new issue just reopen this one.
