### ISSUE TITLE
[Bug]: Can not login with error number 500

### ISSUE THREAD

**Issue by QishenWU** [Arborator/arborator-frontend#424]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a student who encountered an issue. When she tries to log in, no matter what account or device she uses, she cannot log in, and the interface displays as follows. 
![bug](https://github.com/user-attachments/assets/54d9c039-0b59-4c05-b1c6-ce90625d05d2)
But strangely, only one student has encountered this situation, and at the same time I tried with multiple accounts of my own but had no problem.

### Steps To Reproduce

 log in with google and she falls into the page of server error.

### Project name

Linguistique_de_corpus

**Comment by khansadaoudi** [comment]
@QishenWU Can you give me the username of the student

**Comment by QishenWU** [comment]
> @QishenWU Can you give me the username of the student

Name is Noellie Potet
And the email she uses for login:  noellie.potet@sorbonne-nouvelle.fr

**Comment by khansadaoudi** [comment]
The problem has been fixed
