### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by mbardaji** [Arborator/arborator-frontend#45]
Hi,

I am having several new issues with Arborator Grew. I would like to add new admins and guests in my project (UD_Indonesian) - which was possible last week- but I now always get the message "Network error". It is also not possible to remove admins and guests.
The same happens when I try to upload conllu files. I either get a "Network error" or a "Request failed with status code 400". I also do not understand why, since I was able to upload conllu files before. 
I also get a "Request failed with status code 403" when I try to save annotated trees, but I was able to save trees before.

I have tried these steps from different wifis with good internet connection and it does not work in any of them. Also, I am able to change other settings, so I do not think that the problem lies on the internet connection. 

I would be very grateful if you could tell me how to solve this or where to find information/any kind of guidelines to fix it.

Thank you very much in advance!

**Comment by kirianguiller** [comment]
Hi @mbardaji, 

First I'm sorry for the inconvenience with these errors and I thank you for the issue you committed.

I've just release a patch for fixing the bug you detected (400 error when adding new admins).

However, I can't replicate the error you get when saving new trees, have you still the issue ?

**Comment by mbardaji** [comment]
Dear Kirian,

Thank you for your reply. And also thanks for fixing the error when adding new admins and guests. I've already tried it and it worked!

I am still having the other two issues, namely a "Request failed with status code 403" message when saving trees and a "Network error" when uploading conllu files. 

I don't know whether the saving issue is because the file in the project is too big (5k trees). In that case, the problem will be solved once I am able to upload smaller files (250 trees each).

Thanks again!
Best,
Maria

**Comment by kirianguiller** [comment]
It is indeed because there is a file size limit for security purpose. We will maybe raise the limit in a near future, thanks !
