### ISSUE TITLE
Taking into account the conllus for the annotation settings

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#48]
It would be nice to be able to generate the annotation settings from the conllus in the project.

**Comment by bguil** [comment]
Note that it would be possible with the new services in grew_server: `getPOS`, `getFeatures` and `getRelations` (see: [doc of grew_server](https://grew.fr/usage/grew_server#get-tagset-or-features-from-a-treebank)).

**Comment by kimgerdes** [comment]
thanks a lot, Bruno. we have to integrate that into the frontend.
we had discussed at some point whether we want to propose a standard SUD or UD setup. that might be useful for starting a new project.
i wonder whether we want also to combine things: "add standard SUD relations/pos to the setup", "add the encountered relations/pos to the setup"?
we shouldn't be createing a Rube Goldberg machine (machine à gaz)? ;)

**Comment by khoa-ng** [comment]
Hi.
I've reviewed your message.

But i don't understand a bit about this issue.
Can you explain more about 'SUD' and 'UD'?
I guess they are related to project's annotation settings.
I asked you in the past, but i think i didn't get a proper explanation about them.

Thanks.
Khoa.
