### ISSUE TITLE
verify and warn intersection btw getProject and flask

### ISSUE THREAD

**Issue by gguibon** [Arborator/arborator-frontend#5]
for normal user : show only intersection
for super admin : show warn if sets are different

**Comment by kimgerdes** [comment]
i don't understand. can you be more specific what this is about?

**Comment by gguibon** [comment]
It is dedicated to backend:
1. check the results of grewserver project list and sqlite project list
2. if user is standard: show project only if it is in both databases
3. if user is super admin: show a warning about non coherent struture in porject lists
