### ISSUE TITLE
switching languages

### ISSUE THREAD

**Issue by kimgerdes** [Arborator/arborator-frontend#51]
the language should be chosen automatically by means of the browser's settings:
fr for french users
en for everyone else
this should be shown instead of the world symbol

**Comment by gguibon** [comment]
+ warnings intlify and i18n

**Comment by gguibon** [comment]
+ should be already visible even by default

**Comment by gguibon** [comment]
updated i18n for Vue 3
uses the default browser language if the arborator local variable is not found
removed warning error from import and warnings from translation fallbacks
