### ISSUE TITLE
Fail to upload file

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#58]
I'm trying to upload the file https://github.com/UniversalDependencies/UD_French-PUD/raw/dev/fr_pud-ud-test.conllu which contains 1000 sentences into the project `UD_French-PUD`.

 With the full file, I've got the error: 
<img width="538" alt="fail" src="https://user-images.githubusercontent.com/687155/106640806-c9c3af80-6586-11eb-867e-5620f3ad41ea.png">

After a split in two files of 500 sentences, I succeed to upload the two files successively.

NB: I've got the same error in I try to upload the two 500 sentences files at the same time.

**Comment by LoicGrobol** [comment]
After some trials and errors, it appears that the maximum size for a single upload is 1 MiB.

**Comment by LoicGrobol** [comment]
I suspect if has to do with Flask's [`MAX_CONTENT_LENGTH`](https://flask.palletsprojects.com/en/2.0.x/patterns/fileuploads/#improving-uploads) config key, but its default should be 16MiB so I am not completely sure.

**Comment by kirianguiller** [comment]
The issue was fixed at the same time of #76 .
