### ISSUE TITLE
Coming back from grew-match

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#60]
When we make a request with grew-match, it opens a new window with the results. We can modify a tree in this window. But when we come back to the main window, it is not updated. We need to reload the page manually. It should be done automatically.
Another small bug: when we open a tree before doing a request with grew match, it is not possible to open the tree in the window opened by grew-match.

**Comment by kirianguiller** [comment]
This is important. We don't want to have un-updated trees. We can force an auto-reload ?

**Comment by kimgerdes** [comment]
yes, ideally there would be some "dirty" variable that forces a reload in the background or when the grew selection modification is done.
