### ISSUE TITLE
Deletion of a relation is bugged

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#62]
When I work on a selection of grew-match and I delete a relation, it is no longer possible to save the tree.
It is possible to continue the analysis and to add a new relation instead of the deleted relation, but  it is no longer possible to save the tree. I tried different configurations and never be authorized to save the tree.
The bug only exists if you start from a tree proposed by grew-match!

**Comment by kirianguiller** [comment]
This work now. I don't know when it was fixed. Closing the issue.
