### ISSUE TITLE
Position of the window when a tree is opened or when a dependency is added

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#63]
When we click on the icon of a tree, the tree opens and it should be visible in the window. But the line with the icons doesn't move and the tree which opens below can be not visible.
Conversely, when we add a dependency, sometimes the window content moves and the window is centered on the line with the icons. (It happens when the tree is particularly heigh). In this cas the content window shouldn't move or if it moves, the bottom of the tree should be visible.

**Comment by kimgerdes** [comment]
Could you give as an example or an image?

**Comment by khansadaoudi** [comment]
This is an old issue, it hasn't been mentionned since that time so I will close it.
