### ISSUE TITLE
Last tree must be highlighted

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#67]
When we collaborate to a same annotation, it is very important to start with the most recent tree. But it is not very clear what is the order of the different tree and which tree is the last one.
I don't have a perfect solution to propose. One solution could be to highlight the last tree. But for another project, I could prefer to have my tree more visible than other.
Another solution could be to have the possibility to order the trees by dates or by users (with my tree first).

**Comment by kirianguiller** [comment]
I will work on this now. Thanks for your suggestion !

**Comment by kirianguiller** [comment]
Hi, I just pushed an update to order (from newest to oldest) the trees and give an information about when the tree was edited. 
Is it ok ? :)

**Comment by sylvainkahane** [comment]
super 
ca peut être ambigu dans certains cas


mais pas grave car c’est maintenant clair que l’arbre de gauche est le dernier

**Comment by kirianguiller** [comment]
Cool !

C'est où que tu penses qu'il y a une ambiguïté ? Pour l'indication de temps
?

**Comment by kirianguiller** [comment]
Yes en effet. Bon, pour le moment, vu que l'arbre de gauche est le plus récent, ça devrait pas poser trop de pb.
