### ISSUE TITLE
Loosing data after saving?

### ISSUE THREAD

**Issue by ud-portugues** [Arborator/arborator-frontend#69]
Dear colleagues, we have a team of annotators working on a corpus and some of them said that Arborator-grew did not save some changes that they made at the POS tag level (even after they clicked on the save option).

Have you noticed some kind of failure like this in the tool? Do you know if it is possible to retrieve the log of the actions in order to check if this really happened?

Thanks!

**Comment by kirianguiller** [comment]
Hi @ud-portugues , I am sorry for replying you this late. Do you still have the issue ? We worked for improving some of the logic this week, and I think your problem should not exist anymore.

**Comment by kirianguiller** [comment]
For your second point (retrieving the issue), it should not be possible. If you saved but still can't retrieve your changes, it means that it was a frontend issue, and that the backend never received you changed :/. I will still check to see if there is anything in the log ! When wad it exactly ?

**Comment by ud-portugues** [comment]
Hi, Kirian. I think we discovered what the problem is. If an annotator is analyzing a sentence and then, for some reason, s/he scrolls the screen (e.g., to check how s/he has annotated another similar sentence), Arborator-Grew loses the not saved analyses. For this reason, we have recommended that the annotators save each analyzed sentence before scrolling.

**Comment by kirianguiller** [comment]
Ah, good to know the reason. Yes we have a lazy loading logic on scrolling, and this result in loosing information on trees when they are too far from the scrolling point. 

We will close the issue and think about a way of alerting the user before some data are lost because out of sight !

Thanks :)
