### ISSUE TITLE
metadata editing bug

### ISSUE THREAD

**Issue by RZiane** [Arborator/arborator-frontend#70]
Hi, 
We have an issue with editing metadata, we have a sentence translation metadata for our language that can't be edited through the interface. 

![image](https://user-images.githubusercontent.com/77019730/117340173-e8488800-aea0-11eb-8448-e3dfb4287342.png)

The interface works but there is no change after validation. 

![image](https://user-images.githubusercontent.com/77019730/117340366-162dcc80-aea1-11eb-8cef-3cd855b311c9.png)

Thanks in advance.
Rayan

**Comment by kirianguiller** [comment]
Thanks Rayan, I pushed a fix on production. It works here, but tell me if you still see the problem :)
