### ISSUE TITLE
Equal sign in conllu

### ISSUE THREAD

**Issue by RZiane** [Arborator/arborator-frontend#71]
Hi,
We have an issue due to the use of the equal sign in conllu informations.

There are equal signs in one of our metadata and in our MISC column. These signs are used to describe the presence of clitics in our morphological tokenization, so they are essential for our analysis. Moreover everything after the equal sign disappears at upload and therefore at export too. 
But no problem with the `text=` metadata.

I guess this is because the information is supposed to be declared after the =. 

![image](https://user-images.githubusercontent.com/77019730/117342486-98b78b80-aea3-11eb-9d4b-ba3a3667dd74.png)
 
If you could solve this problem we would be very grateful. 
Thank you for your time.
Rayan

**Comment by kirianguiller** [comment]
Hey Rayan, thanks for your help !

The issue should be fixed by now. Here a screenshot of a working use of equal sign in the attribute : 
![image](https://user-images.githubusercontent.com/35531073/117440310-2e9af700-af34-11eb-9ae5-056f7b526d58.png)
