### ISSUE TITLE
implement web socket for live update

### ISSUE THREAD

**Issue by kirianguiller** [Arborator/arborator-frontend#74]
## Needed
It would be nice to implement a websocket communication to allow : 
- live update of trees (one user save his tree, other users see this new tree appearing instantly)
- information on who is connected on the same project/sample/tree

## How to reach it
We could use [flask-socketio](https://flask-socketio.readthedocs.io/en/latest/) library on backend and [socket.io-client](https://github.com/socketio/socket.io-client) on npm module on frontend. I used the frontend one (coupled with the npm backend socket.io library) for a side project last year so I can help to integrate this (huge) feature.

**Comment by gguibon** [comment]
I would recommend a robust solution for this as many users will use it. Such a solution can be RabbitMQ : https://www.rabbitmq.com/web-stomp.html.

**Comment by khansadaoudi** [comment]
I close this issue since we have already a prototype for the sockets that was done by Kirian in [add-socketio](https://github.com/Arborator/arborator-frontend/tree/add-socketio) branch
