### ISSUE TITLE
Bad requests with non alphabetic characters

### ISSUE THREAD

**Issue by lflage** [Arborator/arborator-frontend#75]
When I created a project in arborator grew called "Is sci-fi literature?" I was unable to upload conll files as the button was not "clickable". I noticed that I was not added as an admin to the project and every alteration I tried I got the message "Request Failed with Status code: 405"

I have an account created with github, if that is relevant.

**Comment by gguibon** [comment]
Fixed. Project need alphanumeric characters as for a folder creation. Added modification in the backend creation process.
