### ISSUE TITLE
Explicit error for file limit size reached while uploading

### ISSUE THREAD

**Issue by gguibon** [Arborator/arborator-frontend#76]
Right now, the server only returns 403 error. It may be better to handle this error in a more humanly readable way.

**Comment by bguil** [comment]
Is it related to #58 or something else?

**Comment by gguibon** [comment]
Thanks, it may be. But the error message is different. (403 vs 413)

**Comment by kimgerdes** [comment]
It should be a max size of 200k tokens and a good error message if it's bigger.
