### ISSUE TITLE
Relation table request imply too much computation

### ISSUE THREAD

**Issue by kirianguiller** [Arborator/arborator-frontend#79]
Short term : remove the button on the frontend

Long term : We should rethink the logic of the functionality on both servers

**Comment by bguil** [comment]
A new service `relationTables` is available in Grew-server (see [doc](https://grew.fr/usage/grew_server/#relation-tables)).

 * [ ] update Flask / front-end accordingly

**Comment by kirianguiller** [comment]
It was fixed with #111
