### ISSUE TITLE
Splitter ou ajouter un token

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#8]
Lorsqu'on développe un treebank pour une langue non encore décrite, on est amené à changer la tokenisation au cours de l'analyse.

On peut avec une règle grew, faire ça, mais la règle va s'appliquer à tous les tokens correspondant au pattern. Ce qui serait bien serait de pouvoir le faire pour un token donné, celui sur lequel on vient de cliquer. L'avantage de le faire avec une règle grew est de pouvoir décider quelle partie hérite du lien entrant ou des liens sortants, quelle partie hérite des traits. (On peut imaginer qua la règle grew est plus ou moins cachée mais dans un premier temps ce n'est pas nécessaire, on verra à l'usage quel genre de modifs on fait souvent.)

Pour que la règle grew s'applique au token courant, peut-être faut-il que chaque token ait un identifiant unique.

Problèmes potentiels à résoudre :

- mise à jour du sent_id lors de l'ajout d'un token

- gérer l'application éventuel de la règle aux autres utilisateurs

**Comment by kimgerdes** [comment]
c'est déjà fait. ouvre un arbre et sélectionne la partie du mot ou le groupe de mot que tu souhaites dans le texte au-dessus de l'arbre. vérifie aussi comment les traits sont copiés.
il y a encore une bogue quand le texte ne correspond pas à la suite des tokens. et aussi ça marche mal pour le chinois car on n'a pas d'espace.
