### ISSUE TITLE
Improve and fix the lexicon table

### ISSUE THREAD

**Issue by kirianguiller** [Arborator/arborator-frontend#86]
- [x] search bar is not working
- [x] ordering on other feature than FORM doesn't work
- [x] click on the frequency number to see the usage of a lexicon inside the given sample(s)
- [x] the header of the table has invisible background, which make it in superposition with the table on scroll
- [x] fix/reimplement import/export
- [x] add a close button
- [x] when opening the lexicon table, ask the user to choose the feature (at the moment, it's by default [FORM, LEMMA, POS, FEATS.Gloss]) modify here : https://github.com/Arborator/arborator-backend/blob/main/app/lexicon/controllerV2.py#L30
- [x] add prune compatibility, to be able to see , for a lexicon based on [FEAT_BASE_1, ..., FEAT_BASE_N], its variations on a second list of feats [FEAT_VAR_1, ... , FEAT_VAR_M] (see grew doc here : https://grew.fr/usage/grew_server/#--dev--the-getlexicon-service)

**Comment by khansadaoudi** [comment]
The subtasks are done i can close this issue
