### ISSUE TITLE
make transition to quasar 2

### ISSUE THREAD

**Issue by gguibon** [Arborator/arborator-frontend#87]

**Comment by kimgerdes** [comment]
looks doable: https://quasar.dev/start/upgrade-guide

**Comment by kirianguiller** [comment]
I started the migration on the [quasar_v2 branch](https://github.com/Arborator/arborator-frontend/tree/quasar_v2) . You can there see a TODO list of the remaining (detected) task to do. We probably have some other bug/migration to apply that we didnt detect yet :)

**Comment by kirianguiller** [comment]
Here is an issue I just opened on Quasar official repo about the main problem we have so far : the static file not loading. 
https://github.com/quasarframework/quasar/issues/11200

**Comment by gguibon** [comment]
I think we can close this issue now
