### ISSUE TITLE
Deletion of a relation

### ISSUE THREAD

**Issue by perrier54** [Arborator/arborator-frontend#9]
There is no way to directly delete a relation, which is unnatural. Deletion is only the indirect consequence of adding a new relation with the same target. I understand that the advantage of this is that the tree structure is always preserved.
First of all, this should be explained in the Arborator guidelines.
Second, I think it would not be difficult to implement relation removal  and add the tree structure check.

**Comment by kimgerdes** [comment]
done. to be pushed onto production asap.
