### ISSUE TITLE
Problem uploading new conllu files on arboratorgrew.elizia.net

### ISSUE THREAD

**Issue by olesar** [Arborator/arborator-frontend#92]
I see "Internal Server Error" when uploading files now, even when uploading files that have been previously uploaded (a month ago) and then deleted from the project. I tried different files all of those are valid according to the UD official validation script.
The only "success" is,  when I click upload without files.

**Comment by kirianguiller** [comment]
Thanks Olesar. We just fixed it. It works here on my side, can you confirm me its also the case for you ? Thanks !

**Comment by olesar** [comment]
It works on my side, too. Thanks a lot!
