### ISSUE TITLE
switching account

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#93]
when you change your login, you are sent back to the project page instead of staying on the page where you are. Could we at least stay on the treebank we are on? I often do this operation when I develop a project in exercise mode: I make the demo with a "student" account and I switch to admin mode to correct a problem.

**Comment by kirianguiller** [comment]
Can try to fix this. But for more efficiency, I suggest to just open two times the web browser. One time in incognito (private) mode, and one time in normal mode.

**Comment by kimgerdes** [comment]
I agree that switching users can send to the home page and parallel sessions can be handled a @kirianguiller explained.
However, I'd love to be send to the project page when logging in instead of the homepage (giving general information about AG)

**Comment by khansadaoudi** [comment]
Now, when you log in you're send to the projects pages so I close this issue
