### ISSUE TITLE
more explicit message for double project creation prevention

### ISSUE THREAD

**Issue by gguibon** [Arborator/arborator-frontend#95]

**Comment by gguibon** [comment]
When we want to create a project with a name that already exists, it returns a 500 error. This would be better to directly explain the problem to the user.

**Comment by kirianguiller** [comment]
I don't know when we fixed this (I did some refactoring/cleaning in the error handling logic just now, but not sure if this is the reason of the fix), but it now does give a good explanation of the error : 
![image](https://user-images.githubusercontent.com/35531073/190218610-17490028-4129-4881-8cc5-070691fcca4a.png)

Thanks
