### ISSUE TITLE
Generate grew rule in "Modified Lexicon" interface

### ISSUE THREAD

**Issue by RZiane** [Arborator/arborator-frontend#99]
Hi, 
I tried to generate a grew rule using this button but it doesn't work: 
![image](https://user-images.githubusercontent.com/77019730/145473633-ec500ee3-89a2-4e6b-b5a3-baf908a277ff.png)

Do you have an idea ?

**Comment by bguil** [comment]
The "Lexicon" and "Grew rule" features in ArboratorGrew are broken. We are working on it and a new version will be available in a few weeks.
Sorry for the inconvenience.

**Comment by bguil** [comment]
After a bit more than a few weeks… the `Grew rule` functionality is back.
Note that each output graphs should be saved independently (see #128)
